#!/bin/sh

# Correct the following paths if necessary (should work for redhat)
MIMEDIR=/usr/share/mime-info
ICONDIR=/usr/share/pixmaps

# You shouldn't have to edit these...
ICONS="terminatorX-app.xpm terminatorX-mime.xpm"
MIMEFILES="terminatorX.keys terminatorX.mime"

echo -n "Installing icons in [$ICONDIR] ... "
cp $ICONS $ICONDIR
echo Done.

echo -n "Installing mimetype in [$MIMEDIR] ... "
cp $MIMEFILES $MIMEDIR
echo Done.

