/*
    terminatorX - realtime audio scratching software
    Copyright (C) 1999-2002  Alexander König
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
    File: tX_icon.c
 
    Description: The tX WM-Icon
		 
*/    
/* XPM */
char * tX_icon_xpm[] = {
"48 48 101 2",
"  	c None",
". 	c #2A1D26",
"+ 	c #848281",
"@ 	c #625F5D",
"# 	c #BFBEBD",
"$ 	c #544F4D",
"% 	c #AEAEAC",
"& 	c #484447",
"* 	c #A5A3A1",
"= 	c #483C43",
"- 	c #7A7877",
"; 	c #908F8D",
"> 	c #41343D",
", 	c #E0E1DD",
"' 	c #746060",
") 	c #3A2E39",
"! 	c #9E9183",
"~ 	c #705151",
"{ 	c #DDDAD5",
"] 	c #756663",
"^ 	c #9B8283",
"/ 	c #917C73",
"( 	c #322A32",
"_ 	c #604E51",
": 	c #DED6CC",
"< 	c #D6BA8A",
"[ 	c #614748",
"} 	c #6A6662",
"| 	c #A29786",
"1 	c #D6CCC4",
"2 	c #322632",
"3 	c #BEB29A",
"4 	c #B29B86",
"5 	c #847865",
"6 	c #968471",
"7 	c #7F6967",
"8 	c #BAA282",
"9 	c #62544C",
"0 	c #56363B",
"a 	c #AA9B95",
"b 	c #D1CEC5",
"c 	c #3A2235",
"d 	c #5B3D3D",
"e 	c #58484E",
"f 	c #31222D",
"g 	c #ABAAA6",
"h 	c #9C9693",
"i 	c #BABAB9",
"j 	c #76726E",
"k 	c #D2CAC4",
"l 	c #959694",
"m 	c #A69B92",
"n 	c #49333B",
"o 	c #877B6C",
"p 	c #828682",
"q 	c #80715F",
"r 	c #83615E",
"s 	c #6E605C",
"t 	c #5A5A58",
"u 	c #6A5759",
"v 	c #F6F6F2",
"w 	c #B2A39A",
"x 	c #AC928A",
"y 	c #9C9B98",
"z 	c #503C42",
"A 	c #C5B7A2",
"B 	c #7E7E7C",
"C 	c #B8AEA0",
"D 	c #625A59",
"E 	c #6C6C6B",
"F 	c #362231",
"G 	c #948882",
"H 	c #877C79",
"I 	c #422E37",
"J 	c #9E9191",
"K 	c #6A5F5F",
"L 	c #96908C",
"M 	c #B5B4B1",
"N 	c #CAC2B7",
"O 	c #ABA59D",
"P 	c #7C5656",
"Q 	c #8E8276",
"R 	c #83716D",
"S 	c #715856",
"T 	c #504449",
"U 	c #5A5053",
"V 	c #888888",
"W 	c #C2C2C2",
"X 	c #C2B8B6",
"Y 	c #311E28",
"Z 	c #B7A8A0",
"` 	c #9C8985",
" .	c #3E2A32",
"..	c #372632",
"+.	c #7E605E",
"@.	c #6A4E50",
"#.	c #6A4A46",
"$.	c #786B6A",
"%.	c #625457",
"&.	c #A29C98",
"*.	c #8E8784",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                              y *                               ",
"                                                            # Z Z {                             ",
"                                                            N / | , W y                         ",
"                                                      p ; V x Z 1 : Z $.y                       ",
"                                          E - + B j E } K S ` w 8 b m $.$.l                     ",
"                - - H D > = & = & = > ) ) ) > > = $ u K T u x r / a X | K j                     ",
"  J G a Z ! ' u 9 =  .2 ( f f f f f f 2 2 2 2 ) e R V %.T > @./ x 6 J J z U +                   ",
"  ` 7 C b X _ n ..F f f f Y Y Y f f f 2 f K %.*.*.J *.%.....f z z e > j ` K K ;                 ",
"  w 7 s 7 S 0 F F Y f Y f Y Y f Y f F  .%.G y # - U > 2 F 2 f ..f .  .T J m s } +               ",
"  k R #.[ [ Y Y Y Y . Y Y . .  .> = s a &.J + = 2 2 2 F Y F F  .c  .[ $ $.O K e E               ",
"  1 / @.~ d Y Y Y . Y Y Y Y Y ' J * ` V R & c . F F c F c F ..n [ ..e _ H *.%.T e -             ",
"    Q @.P ~ Y Y . Y . Y c c $.*.H &.@ = 2 f f . f f c F c F ..z +.e > = _ U %.U z $ -           ",
"    L ~ r R  .Y  .[ / ] w X W *.} ) Y f f f f f f c c F c I U S +.u U u = e %.%.e T s -         ",
"    6 ' +.r P I q 5 a L g - u F Y f f . f . . f c c c > $.R / ^ 5 7 / 3 U 7 Q H 7 o | ` &.      ",
"      ' S P P S e ..U j = ..F Y . f . f f . Y . c u ^ ' k l ; V G L ; M a C M h L L ! h *.g     ",
"      q [ ~ d 0 #.z I ..Y Y Y F Y f . . Y f c I ' ; J ' { V E E } E } ; N # { + j j ; - 9 t     ",
"      o 9 _ d d I d @.S D _ = ....c c c ..n u ` h V a U a * V V ; + - B % y , y E E ; @ $ T &   ",
"        S +.! R d 0 #.R / / ` L h J J x * a J a j B h $ P h % M M i M M g G g % y l G 9 & & &   ",
"        q d 6 7 7 7 u R ^ ^ ^ ^ ` ` J ` ^ Z L l V y J U T $.y M i M i # M *.9 H % % % $ = > =   ",
"        H [ C N { 1 S $.R H G H 7 7 R 7 ^ &.l V ; l w m 4 u ; i W W W W W &.E 5 &.{ % & = e     ",
"        G u Z X * H %.D %.%.u e z z z 7 l ; - - - V L l Q > / % W W W # # % o K M v + = $       ",
"        w ' z z = n n n I ) n > > I ) R h J - - - ; H - j $ K L M # W # # i ! $.*.| 9 u j       ",
"        * K I  . .n > ) I I ) I I  .n I e l + - - l q $ e K H L M W # # W W % Q t t t %.        ",
"          [ > I  . .I ) I I I I n z u s $.y l l ; y q t       4 * W W W W W i ! s               ",
"          $.n I n I z 0 _ 7 V H           y % M g * q $         h i W W W W W % 5               ",
"          L 0 n 0 0 %.                    * i i M % 5 $         ! * W W W W # i *.              ",
"            [ [ e e _                     * # i # % q $       A   # % % % % * g &.$.            ",
"            K Y . (                       * W # i % H $     o Z k , * V ; ; V ; y |             ",
"                                          * M % M % 6 $     Q % b b M E } E E j - M *           ",
"                                          &.% g g * 5 $   < l p { y | p V ; B B j V N           ",
"                                          &.* % g g 5 $   A p p L Q 6 p j } E @ } E W +         ",
"                                          * M # i g ; $ 8 h @ E E ! q | } t t t @ t ; O         ",
"                                          y % M i &.m $ m p E E j ; ! O - E E } @ @ B { O       ",
"                                          m *.B B H 6 t | O g O g 3 M ] ; * O g g O O N y       ",
"                                                            @ @ @ @ t                           ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
