/*
    terminatorX - realtime audio scratching software
    Copyright (C) 1999  Alexander König
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
    File: tX_smlog.c
 
    Description: Small terminatorX-logo
*/    

/* XPM */
static char * tx_smlog_xpm[] = {
"40 280 256 2",
"  	c None",
". 	c #030304",
"+ 	c #908357",
"@ 	c #454444",
"# 	c #86461C",
"$ 	c #C5C4C2",
"% 	c #646464",
"& 	c #252213",
"* 	c #A9A488",
"= 	c #67431F",
"- 	c #512709",
"; 	c #88693E",
"> 	c #AD854D",
", 	c #A86828",
"' 	c #343434",
") 	c #695338",
"! 	c #88764C",
"~ 	c #78725C",
"{ 	c #E6E2C4",
"] 	c #979282",
"^ 	c #CEA258",
"/ 	c #595242",
"( 	c #3B2412",
"_ 	c #220E04",
": 	c #AD925E",
"< 	c #7A633E",
"[ 	c #785523",
"} 	c #51371B",
"| 	c #9B8454",
"1 	c #58432A",
"2 	c #B3B299",
"3 	c #966932",
"4 	c #D5D4D0",
"5 	c #7E4417",
"6 	c #633D1A",
"7 	c #987949",
"8 	c #2C2C2B",
"9 	c #49341A",
"0 	c #F4F4EF",
"a 	c #C29249",
"b 	c #B6A26C",
"c 	c #5B391B",
"d 	c #766A34",
"e 	c #9A8A54",
"f 	c #574A2E",
"g 	c #141413",
"h 	c #694C26",
"i 	c #8B6F3D",
"j 	c #695A3F",
"k 	c #3F2C14",
"l 	c #8A581F",
"m 	c #CEB274",
"n 	c #241C0F",
"o 	c #AF9A6F",
"p 	c #785B31",
"q 	c #9E5E1C",
"r 	c #6C6C6C",
"s 	c #E2C26C",
"t 	c #7F7A68",
"u 	c #A59B7A",
"v 	c #433A24",
"w 	c #A87838",
"x 	c #5C5C5C",
"y 	c #88602D",
"z 	c #BE8234",
"A 	c #877962",
"B 	c #8E8B79",
"C 	c #302316",
"D 	c #523E28",
"E 	c #D4C294",
"F 	c #B1AD94",
"G 	c #E3E3E3",
"H 	c #331D0A",
"I 	c #524A39",
"J 	c #472C19",
"K 	c #E2D2A4",
"L 	c #987E53",
"M 	c #C7B59C",
"N 	c #F3E9D3",
"O 	c #716346",
"P 	c #AC8C4F",
"Q 	c #747474",
"R 	c #816440",
"S 	c #594D42",
"T 	c #B77629",
"U 	c #BFBB9F",
"V 	c #976F35",
"W 	c #988B79",
"X 	c #704C24",
"Y 	c #785D40",
"Z 	c #615337",
"` 	c #352B1F",
" .	c #685D54",
"..	c #120A04",
"+.	c #B0A488",
"@.	c #906836",
"#.	c #A19474",
"$.	c #B89456",
"%.	c #FDFDFA",
"&.	c #1C1C1A",
"*.	c #897052",
"=.	c #2B1D12",
"-.	c #6F5432",
";.	c #A38554",
">.	c #786D56",
",.	c #3D2C1F",
"'.	c #70451C",
").	c #513926",
"!.	c #604322",
"~.	c #463D37",
"{.	c #95612A",
"].	c #362516",
"^.	c #4F3012",
"/.	c #3C3C3C",
"(.	c #774D24",
"_.	c #AC9D7F",
":.	c #89826F",
"<.	c #4F422B",
"[.	c #CDCCC9",
"}.	c #473427",
"|.	c #C0AC7A",
"1.	c #A48D65",
"2.	c #A97E47",
"3.	c #867E71",
"4.	c #7F7468",
"5.	c #8E7E54",
"6.	c #5C3E1F",
"7.	c #935922",
"8.	c #7F5C2F",
"9.	c #D8B26C",
"0.	c #E2BE94",
"a.	c #E3DCCB",
"b.	c #E2CA98",
"c.	c #D2CAB4",
"d.	c #CBAA64",
"e.	c #C09C5C",
"f.	c #DDDCD9",
"g.	c #BA8A4C",
"h.	c #ECECE9",
"i.	c #C8BCA6",
"j.	c #A86F2E",
"k.	c #0D0C08",
"l.	c #CABE8C",
"m.	c #E2BA64",
"n.	c #89511F",
"o.	c #2F1607",
"p.	c #B87E38",
"q.	c #B0621C",
"r.	c #CE9644",
"s.	c #5C300C",
"t.	c #D6AC60",
"u.	c #F5EEE1",
"v.	c #79542E",
"w.	c #B4B4B4",
"x.	c #B6A68C",
"y.	c #9C9C9C",
"z.	c #E2D6CC",
"A.	c #AA8A5F",
"B.	c #966E48",
"C.	c #B7AB94",
"D.	c #160E06",
"E.	c #B89D67",
"F.	c #F0C478",
"G.	c #918470",
"H.	c #D6BA84",
"I.	c #6F3E17",
"J.	c #B38446",
"K.	c #EFE3B4",
"L.	c #DCD2B4",
"M.	c #A17841",
"N.	c #ECDEC0",
"O.	c #D0BA94",
"P.	c #A3A3A4",
"Q.	c #CAA571",
"R.	c #A2968C",
"S.	c #251608",
"T.	c #70655B",
"U.	c #5F5449",
"V.	c #CCC6B7",
"W.	c #90774E",
"X.	c #807256",
"Y.	c #442512",
"Z.	c #FCF4E4",
"`.	c #EBE5D4",
" +	c #804D1C",
".+	c #AF966E",
"++	c #BF965E",
"@+	c #866240",
"#+	c #ACACAC",
"$+	c #BCBCBB",
"%+	c #4F321D",
"&+	c #D4CDC1",
"*+	c #3C342B",
"=+	c #7F551C",
"-+	c #BBB597",
";+	c #A06829",
">+	c #C1A46A",
",+	c #826B40",
"'+	c #614A2E",
")+	c #1B150B",
"!+	c #715B3F",
"~+	c #AF792F",
"{+	c #B48C4A",
"]+	c #604D3E",
"^+	c #BF792C",
"/+	c #9F7135",
"(+	c #6F5D4C",
"_+	c #8F6F4C",
":+	c #806B4F",
"<+	c #C58D41",
"[+	c #B0702A",
"}+	c #A69A8C",
"|+	c #B48E64",
"1+	c #A17E50",
"2+	c #AF7E3F",
"3+	c #917E5F",
"4+	c #67452E",
"5+	c #77654E",
"6+	c #684D36",
"7+	c #D6C6A8",
"8+	c #504640",
"9+	c #A27A5C",
"0+	c #0B0604",
"a+	c #242424",
"b+	c #949494",
"c+	c #545454",
"d+	c #998466",
"e+	c #9C8C6A",
"f+	c #87592D",
"g+	c #C9B588",
"h+	c #7C7C7B",
"i+	c #8C8C8C",
"j+	c #4C4C4C",
"k+	c #848484",
"l+	c #C9AE77",
"m+	c #EED6BC",
"n+	c #6A655F",
"o+	c #B2935C",
"p+	c #563716",
"q+	c #6A3E19",
"r+	c #92713D",
"s+	c #726C65",
"t+	c #4A3B27",
"u+	c #625D56",
"v+	c #8E5E24",
"w+	c #C68434",
"x+	c #8E7962",
"y+	c #3A1E07",
"z+	c #EAD6B0",
"A+	c #7A746A",
"B+	c #9E8E74",
"C+	c #7E5E3C",
"D+	c #A6966C",
"E+	c #56310F",
"F+	c #DACDAC",
"G+	c #9E7254",
"                                                                                ",
"                                                                                ",
"                                                                                ",
"        . .                                                                 .   ",
"    V ].. . . .                                                       ' u+8 .   ",
"  {+ .H ( & 0+. . . .                                             k./ 4 %.7+g   ",
"  | r j+a+S.H S.0+. . . .                                     g n W h.G [.o &.  ",
"  v.% % r c+*+n 6 J &.&.k.0+.                           &.' 3.i.U k+h+r Q #.&.  ",
"  X r /.@ % % x j++.{ $ b+r ' 0+.                   . C V.L.4 $+s+@ &.g c+D+&.  ",
"  X n+/.a+&.8 x n+x P.h.%.%.$ *+                . ].< l+[.#+c+' 8 g D.k.x D+&.  ",
"  X % /.a+&.&.' Q k+Q k+f.%.`.L             k.k 9 ) T.r x 8 a+g &.g g k.c+_.&.  ",
"  X r ' a+a+&.' Q b+y.i+h+P.B 1.      . )+).} t+c+s+Q c+&.a+8 g a+&.k.g c+u n   ",
"  (.r /.a+a+a+@ k+k+% c+8+; r+    . ( 1 1 S c+r i+Q c+j+&.8 ' g &.&.k.k.c+* )+  ",
"  v.n+/.a+8 @ h+r j+).< 8.    k.9 !.]+/ % Q y.y.h+x c+@ &.8 ' g &.g k.g j+* n   ",
"  (.Q c+x i+w.$+;.,+    . n 9 } <.c+% k+y.y.y.b+r j+j+@ &.' @ &.&.&.k.g j++.S.  ",
"  v.Q w.4 G %.u.!+  . ` 6.9 @ c+% i+P.y.P.P.P.b+Q c+j+/.g ' @ &.&.g g &.j+* S.  ",
"  6 B 0 %.{ y./ &.} 9 v I c+% i+y.y.P.y.y.y.y.y.k+x j+' g @ j+&.g g k.&.j++.S.  ",
"  <+++o i+~.& ) '+v c+x h+b+b+b+y.P.y.P.P.P.P.y.k+x @ ' g /.x 8 k.k.g &.j++.y+  ",
"      @ u+#.C.x+x x h+y.y.y.b+b+y.P.y.y.y.y.y.y.k+% @ ' g @ x ' g g g a+j+>.    ",
"    l.z.G B r h+y.b+y.y.P.b+b+b+y.y.P.P.y.P.P.P.i+% @ ' g /.x /.&.g ' @ j+).    ",
"  J.w.F Q j+' % y.b+y.y.P.y.y.b+y.y.y.P.y.y.y.y.k+% @ ' g /.x ' /.c+s+; V       ",
"  P s+j+a+a+8 r y.b+y.y.y.y.b+y.y.y.P.y.P.y.P.P.i+x @ ' &.a+@ j+U.; V     0+.   ",
"  _+% 8 &.&.8 r y.b+y.P.P.P.y.y.y.y.P.y.P.y.y.P.i+c+j+% r % 6+@+v.    & :.d+&.. ",
"  p r 8 &.&.' h+y.i+b+P.y.y.y.y.y.P.y.P.y.y.P.y.i+i+b+$+f.|+[   . S.p+r+4 L.v . ",
"  7.r 8 &.&./.k+y.i+b+P.P.y.y.y.y.P.y.y.y.y.k+% h+4 %.N C.1 &.n 6 ; 4.c+% F v . ",
"  Y % 8 &.a+j+b+i+k+y.y.y.P.b+b+y.y.P.P.i+% c+@ o 0 2 u+y.$ M 7 j j+' &.j+* *+. ",
"  y % a+g a+c+y.i+h+b+P.y.P.b+b+y.b+r x c+8+C+        L %.%.$ x 8 &.&.&.j+* *+. ",
"  R % 8 &.a+c+b+k+k+b+y.P.y.b+Q % c+S !+M.        $.F+-+[.w.c+/.j+a+g &.@ * v . ",
"  ; % a+&.a+c+b+k+h+b+y.y.Q x j+~.!+~+          d.>.c+% x a+&.@ j+a+g &.j+* *+. ",
"  R % a+&.&.c+y.k+h+Q r x @ }.8.                  9 *+@ r c+' /.@ g g &.@ * v . ",
"  ; % a+&.a+j+b+c+c+j+@ -.3                           - ` r r j+/.g k.&.j+* v . ",
"  ; r 8 a+/.r x j+).f+w                                   <+$.] Q % j+&.j+* D   ",
"  R r % h+b+:.8.@.                                            s J.S % % j+W [   ",
"  !+i+$ h.Z.9.                                                    J.v.j % S     ",
"  M G Z.K                       . . . . .                               o+4+    ",
"                              D.g D.0+. . .                                     ",
"                            h 8.! x+i ^.. . .                                   ",
"                        P L j+j+j+/ % +.'.0+.                                   ",
"                        o r k+i+b+h+x c+e+( .                                   ",
"                      | % y.y.P.y.b+b+% x v...                                  ",
"                      !.Q y.y.P.P.b+i+h+c+< S.                                  ",
"                      L r y.y.y.y.i+k+i+x <.=.                                  ",
"                      { b+y.P.y.y.i+3.h+r +.                                    ",
"                      %.0 y.y.y.b+b+k+k+x r+                                    ",
"                      { %.i+% k+b+b+k+Q |.+                                     ",
"                        e.o j+j+r r A+) d D.. 0+. . . . . 0+. . . . . . . . .   ",
"                          ,+! >.G.E.r+).)+n 1 T.].C ` S.( n+/ k H ` ` 8 ` &..   ",
"                      m.5+(+>.>.:.O *+).6.:+V.G >.f -+] F u.V.t+` j 1+7 B.L D.  ",
"                      R r Q r r r n+r r r % % r s+u+@ c+c+x x s+Q x j+c+% #.&.  ",
"                      {.c+b+b+b+b+b+k+h+k+b+y.y.Q 8 b+#+P.r &.8 a+g 8 &.c+#.n   ",
"                      /+c+i+i+i+k+h+r x Q b+P.b+c+' P.w.y.x &.8 a+&.' 8 j+#.&.  ",
"                      w j+b+k+h+k+h+r x r i+y.b+/.j+#+#+h+8 &.@ a+&.' 8 j+e+&.  ",
"                      J.j+b+i+h+h+Q % c+% i+y.i+8 x w.P.c+g ' c+8 &.' ' j+1.&.  ",
"                      $.j+b+i+k+Q Q % x % i+y.h+8 % #+b+' g j+% 8 g ' ' @ #.&.  ",
"                      e.j+b+i+i+h+r % x r i+b+r a+h+#+h+a+&.c+r ' g ' ' j+u n   ",
"                      > j+b+y.b+i+k+k+h+k+b+y.Q a+r b+x &.@ Q k+@ &.a+8 @ +.    ",
"                      {.j+c+c+c+x x % x x c+x % r @ @ j+r r % % r r x c+@ :+    ",
"                      f+4+6.y 3 !.} } 6.4+@.f+k 1.4 V.O.D C k }.,.@+>+l.L H     ",
"                                                  } %+t+                        ",
"                                            . . . . . . . . . .                 ",
"                                        . ..=.k ` Y.<.& D.. . . . .             ",
"                                    D.9 6.; Y v * 2 $ p =.Y.=.D.. . . .         ",
"                                k+#.W.v / j+c+n+@ j+j+r c+/.t+(.y+n . . .       ",
"                              A %.4 Q % x Q k+8 i+#+x 8 c+r x j+` k '+0+. .     ",
"                            ; R $ $+P.b+h+b+x /.P.w.% &.a+/.% r x j+6+; . . .   ",
"                          T D+h+P.P.y.k+k+i+' r w.#+Q g &.8 /.r Q % Q p -.. .   ",
"                          H.b+y.b+y.y.k+b+x ' y.w.w.k+a+g 8 /.u+j+8 c+A+y C .   ",
"                        w 3.b+b+y.y.i+k+i+8 r #+$+w.y.j+g a+/.x @ g a+x u+p . . ",
"                        R k+i+y.P.y.i+y.x /.P.w.w.$+#+% g a+/.c+@ g &./.% -.)+. ",
"                      N.$+k+i+y.y.b+b+i+8 Q w.w.w.w.#+Q &.&.' j+/.&.&.a+r ]+1 . ",
"                      Q.i+k+i+y.i+k+b+x 8 b+w.w.w.w.#+% &.a+/.x j+8 &.&.j+s+;.  ",
"                      X x % % c+c+c+% % j+c+c+x x c+j+j+x r r r r % x x j+% a   ",
"                      !.} }.'+W.#.O }.u o *.Y !+< :+e+F :+*+C C ].*+*.d+d+-.H   ",
"                            _ )+)+_ n n )+D.D.D...D._ )+C =.n &.&.=.C ].=.S.. . ",
"                          n ..0+..)+D.0+....0+..0+....k.g g g g g g )+)+)+)+. . ",
"                      F. .p+Y W.!.f * d+R p -.6+-.!+*._.d+D ).).` 9 *.W.X D Z . ",
"                      5.s+% c+x % x c+c+c+c+c+c+c+x c+j+c+r % n+r r % x n+3.;   ",
"                      c x i+b+k+*+c+y.#+#+w.#+#+#+#+#+b+/.g &.&.a+&.&.&.c+3.!.  ",
"                      =+j+k+b+% a+b+w.w.#+#+#+#+#+#+w.#+x g g g g g &.&.j+5+k   ",
"                      q.U.r k+/.@ #+w.#+#+#+#+#+P.#+w.w.Q 8 &.&.g g &.&.j+C+    ",
"                        3 c+h+a+r w.w.w.#+#+P.#+#+#+w.w.b+j+' &.k.g &.8 T.v+    ",
"                        , u+% ' i+w.#+#+#+#+#+P.P.#+#+$+P.Q j+8 g k.g j+++      ",
"                          p.j+c+h+w.#+#+#+P.#+#+P.#+#+w.w.i+% 8 g g g n         ",
"                            Y.h+r h+#+#+#+#+#+#+#+#+#+w.w.y.Q ' a+% !+_         ",
"                              m+h.k+c+h+y.#+#+P.#+#+#+w.w.P.% @ j+; v.          ",
"                              u+M l.t c+j+c+r h+k+k+k+Q r j+@ }.;               ",
"                            . . g     2.{+! O c+c+c+/ '+~.1 C+                  ",
"                        j.=+W.k .             ~+~+/+7.                          ",
"                      $.r % y.I..                                               ",
"          . . . . . ..[ r c+r I.. . . . . . . . . . . . . . . . . . . . . . .   ",
"          )+k.k.k.k.)+@+% ' n+'...k.....k...k.....k...k.....& ` g k.k.k.... .   ",
"    6 5.3 ( ].} 6 6.'+u j+8 % b 8.-.v.X (.X X X (.X v.v.v.i M 0 W.( k C %+C+..  ",
"    w+n+x % c+j+j+j+/ k+8 &.j+j+@ @ @ @ @ @ @ @ @ @ @ @ @ j+% i+h+x j+c+% ,+&.  ",
"      !.j+n+Q h+i+b+b+k+' j+b+P.P.P.P.P.P.P.P.#+P.P.P.P.P.P.P.h+' j+h+Q r e+n   ",
"        =.~.% k+k+y.y.i+8 % w.#+#+#+P.P.P.P.P.P.P.P.#+#+#+#+w.#+j+a+x c+r e+&.  ",
"          o./.x b+y.y.b+a+Q w.#+#+P.P.P.P.P.P.P.P.P.P.#+P.#+w.w.x &.x x r e n   ",
"            %+c+Q k+y.b+8 h+w.#+#+P.P.P.P.P.P.P.P.P.P.#+#+#+w.w.% &.c+x r + &.  ",
"              z+G y.k+y./.i+$+#+P.#+P.P.P.P.P.P.P.P.P.P.#+#+#+w.r &.x x r x+n   ",
"              f.%.4 k+i+c+i+[.w.w.#+P.P.P.P.P.P.P.P.P.P.#+#+w.w.Q &.c+% r x+n   ",
"                a.0 $+P.h+$ 0 $ f.#+2 #+#+#+#+#+#+#+#+#+#+w.w.w.r &.x % r L     ",
"                  N.%.0 $+4 %.0 $ #+i+Q Q Q Q Q Q Q Q Q Q Q r % j+c+% % r 4.    ",
"                    0 %.%.h.%.%.0 }+5+) ]+]+Z ]+]+) ) !+(+O >.3.* c+8+<.s+,+    ",
"                    w.u.N %.%.%.u.|.: W.                        ++              ",
"                      b+u.%.%.%.4                                               ",
"                          Z.%.%.$   8 k.. . . . . . . . . . . . . . . . . . .   ",
"                            0 0 i+a+. . . . . . . . . . . . . . . . . . . . .   ",
"                              W *.4+4+6 6 6 = 4+X -.C+@+i A W.5.5.k Y.^.].k k.  ",
"                            i.m s+@ j+8+j+j+j+j+j+j+j+j+c+x c+x r % c+j+@ *+&.  ",
"                          %.0 $+#+y.y.y.y.y.b+y.y.b+b+b+i+k+h+Q /.@ Q k+% I &.  ",
"                        4 0 %.G #+#+P.P.P.P.#+#+w.w.w.w.w.w.w.#+% &.x Q r ) &.  ",
"                        {+w.h.$ #+P.P.P.#+#+#+#+w.w.w.w.w.w.w.#+r g @ x r R &.  ",
"                        g+b+$+#+P.P.P.P.P.P.P.#+w.w.#+w.w.w.w.w.Q &.8 @ r x+n   ",
"                        (+y.#+P.P.P.P.P.P.#+#+#+w.w.w.w.w.w.w.w.h+a+&.a+r e n   ",
"                      v+/ #+P.P.P.P.P.P.P.#+#+#+w.w.w.w.w.w.w.w.k+a+g g x #.n   ",
"                      X c+#+#+P.P.#+P.#+#+#+w.w.w.w.w.w.w.#+#+#+h+a+g k.c++.    ",
"                      '.j+#+#+b+h+Q Q r r r r % % % % r % x % x j+j+c+j+j+*.    ",
"                      7.@ i+% @ !.f f ) !+O 4.:.] w.w.B B #+$ P.$+A T.d+W }.    ",
"                      q.c+s+{+1 ,.Y.( o.C ( k c   ! Y %+} p + !.Z f 1 / 1 _ .   ",
"                        < P :+-.} ) < q+S.. . 0+    &.~.@ S j+` g g D.g k.... . ",
"                        O.N >+~ j+j+S r P !.. 9 Y A.>+Z.0 %.%.0 &+7 7 D+P e 9 . ",
"                        %.%.V.P.y.b+h+x c+_.^.!.c+Q Q Q r h+Q x x % n+% n+b+l . ",
"                        O.`.f.w.P.P.P.P.x x (.6+r r 8 x h+% r Q @ a+a+' @ h+7.. ",
"                        E.P.w.P.P.P.P.P.y.j+).]+r k+a+% i+r Q h+c+8 /.j+/.h+-.. ",
"                        ~.k+#+P.y.y.P.P.#+r } < r Q ' % i+x c+x ' a+' @ /.s+}   ",
"                        v.r #+P.P.P.P.$+w.i+T.O s+r ' c+k+@ a+8 &.a+' /.@ I 9   ",
"                        ~+j+i+P.P.y.P.$+G [.F+|+:+r @ c+h+8 g k.g g ' ' j+1     ",
"                        [+>.c+k+#+#+$ G %.%.0 Q.7 x c+@ Q a+&.a+g g a+a+Q @.    ",
"                          <+>.j+x Q h+#+0 %.0   ++a+x @ x a+&.8 a+k.&.g D       ",
"                            [+2.Y U./ d+N f.k+    [ 8 r j+/./.j+c+j+x :+o.      ",
"                                                    c @+] Q r r % i+-.=+        ",
"                                        k.g k.0+. . k.D + $._+; B.d }.. . .     ",
"                                  . . . . . . . . . . . . k.0+..D.. . . . . .   ",
"                              H 9 k %+6 X X X X 8.+.D+; ! r+p } Y.- 6.h 8.O 0+  ",
"                          [.g+1.~.@ 8+j+j+j+S j+j+r Q Q Q Q r u+c+x u+r Q ] g   ",
"                        h.%.0 #+b+] i+b+b+b+b+b+b+i+% /.' 8 ' /.c+j+' ' c+u g   ",
"                        %.%.%.4 #+#+#+#+w.w.w.#+#+w.#+j+g g k.g &.g & /.@ ] )+  ",
"                        a.%.h.4 w.#+#+#+w.w.$+w.#+#+w.x g g k.g g g ' x @ B )+  ",
"                      Q.R.$ &+#+#+#+#+w.w.y.y.w.#+#+w.Q g a+g g &.g @ r @ + g   ",
"                      @.~ w.w.P.#+#+w.w.#+Q % P.w.#+w.i+&.8 a+g g g /.Q @ A g   ",
"                      = x #+P.P.#+#+w.w.P./.a+r w.w.w.#+' &.8 a+a+g ' Q j+X.)+  ",
"                      p+x #+#+#+#+#+w.w.y.a+& 8 b+w.#+w.% g 8 8 8 &.8 h+j+>.n   ",
"                      6 j+k+i+i+i+i+i+k+% @ % j+c+k+i+k+x /.% % x j+/.x c+Z     ",
"                      3 x c+c+j+c+c+x c+r % j+j+r % c+j+% Q c+j+j+c+Q Q c+O     ",
"                        z M.8.y y i ; y | !+c } ; | 8.8.W.| 6.,.,.c ; 1.(.8.    ",
"                            0+. . . 0+. . 0+0+0+. 0+. . 0+. . 0+0+0+0+. . 0+.   ",
"                        l < p O ,+e+#.< ,+5.6.} ,+| [ '.[ e i D ^.D < 1.X.'+0+  ",
"                      E.x % % r A+k+:.Q r A+x / r h+% U.% h+~ c+j+S s+h+t u D.  ",
"                      l x A+r x /././.u+r j+/.@ /.@ r h+Q x /.j+c+c+/.@ j+4.)+  ",
"                      l j+P.#+k+j+' x P.w.h+a+D.&.x #+w.w.y.@ g g &.&.r j+:+g   ",
"                      n.@ b+k+x 8 a+x P.#+h+8 k.g @ P.w.w.#+j+g g g &.% j+O )+  ",
"                      n.@ r c+8 &.&.c+P.P.% a+k.g 8 b+w.w.P.j+g g &.&.x j+O g   ",
"                      {.@ @ ' g g g c+b+y.c+&.k.k.a+k+w.w.P.@ g g g g % j+Y )+  ",
"                      /+j+a+&.k.g g @ k+h+/.&.g k.&.h+w.$+y.' g &.&.g c+j+j )+  ",
"                      : j+g k.k.k.k.8 % x a+g k.g g r w.w.k+8 k.&.8 g @ 8+(+n   ",
"                      F+Q @ @ /./././././.' ' /.@ ' @ Q h+j+/.@ c+x j+/.j+f     ",
"                      %.$+r x x x x x % r % r x x % h+y.b+Q % c+c+j+c+Q c+>.    ",
"                      7+Q.3  +(. +6.!.v+@.y v+f+=+l P [.V..+f+q+1 ).'.;.; e     ",
"            . . .           . 0+. . 0+. 0+0+0+. . . 0+g g 0+. 0+. 0+. . . . .   ",
"        0+g k.. . .         0+0+0+. 0+0+. 0+0+0+0+0+k.. . 0+. 0+. 0+0+0+. . . . ",
"      ; ,+(.6 k D.. . D.w -.C =.=.n n C k C C C ].].=.=.=.=.& =.n n n 9 ,+! )+. ",
"    8.t r n+c+n k n . [ x % x x x c+x % % x x x % % % x c+c+c+c+c+c+c+% Q _.- . ",
"  ^ Q r c+@ % x ~.c ..X r c+x % x x 8+/.j+% r % j+/././ r Q h+Q r r s+x u++.s.. ",
"g. .% j+/.a+' Q j+6+].- % c+/.j+/.8 g g 8 j+c+j+8 g g &./.c+% x j+@ c+j+n+F 6.. ",
"{+r % j+j+/.j+k+% c+E+- x x c+x @ &.&.&.' c+% x ' &.k.k.&./.c+c+@ j+x r Q &+i+g ",
"X % r c+j+j+x i+r r C+c % % r h+c+a+g a+j+% r x /.&.g k.g a+/.@ @ j+% h+h+$+W k.",
"J % Q c+c+j+% i+3.y.a._+% Q h+b+% a+&.8 j+Q Q x /.&.k.g k.g a+' @ c+% k+r s+I . ",
"I.j+Q x j+j+% b+h+w.c.5+c+k+i+y.Q a+&.' c+Q Q x /.a+k.g k.k.g &.' c+% Q r 8+D   ",
"  1 % Q c+j+x i+r `.: Y c+i+y.y.Q ' a+/.% h+h+r j+8 g k.g k.g &.8 @ c+r r D (.  ",
"  5 @ % r r Q h+r [+  q j+r % % r % x r Q Q Q Q r r x c+j+j+j+c+x r Q r r s+    ",
"    # ~.j+c+u+A+;+      ~ A+B A+@ /.~./.~.<.@ *+/.' ~.@ x  .n+ .c+@ /.v T.P     ",
"      l p+4+7 g.                                                                ",
"                                            . . . . . . . . . . . . . . .       ",
"                                  . . . . . . . . . . . . . . . . . . . . . .   ",
"                              S.*+) p+=.=.=.n =.=.n n n =.C ].( ( C C =.=.].0+  ",
"                            +.7+#.! c+j+S j+j+j+8+8+j+8+j+j+c+c+j+j+j+j+@ ` &.  ",
"                          I.] Q /.8+j+% r n+x c+x % % % % % u+x % u+x % % I n   ",
"                        G+G.% 8 c+j+g ' x @ 8 &.&.8 /./././.8 8 8 a+a+8 r S &.  ",
"                        `.i+8 j+i+% a+' x @ 8 a+a+8 ' @ j+@ /.' /.' a+' r / &.  ",
"                      M.n+Q a+Q y.Q &./.x c+j+j+@ ' ' @ j+j+@ @ @ /.' ' r S &.  ",
"                      [+j+u+8 k+P.r &./.% Q k+k+% @ /./.@ j+j+j+j+@ ' @ ~ S &.  ",
"                      D+c+@ /.k+i+x g @ r b+y.y.k+j+/./.@ j+j+c+x @ /.@ r 8+&.  ",
"                      o+c+' j+r r /.g @ Q b+y.y.i+x /./.j+@ c+x x j+/./.Q I C   ",
"                      r+c+j+/.@ @ @ j+r Q r x x r r % % r r % r r r % % % t     ",
"                       +j+r Q r r % c+j+c+x r Q % j+j+j+j+j+j+j+j+j+j+j+x !     ",
"                        M.| W.8.y y 6.].J c R X.[ J ].].].` ].k ].` ].` Z h     ",
"                            . . . . . . . . . . . . . . . . . . . . . . . . .   ",
"                        =+:+h p+) !+6.n =.( 6.j '+J =.n =.n n =.=.n =.=.=.C 0+  ",
"                      v+/ Q % x s+Q u+j+S / r h+s+x j+j+j+8+8+j+j+8+j+j+j+` &.  ",
"                      l j+@ @ j+@ @ j+r r r r % n+r s+% % x % % r % % u+% S &.  ",
"                      > @ @ &.&.j+' &.j+r r i+y.y.i+Q j+a+&.8 /.j+/.a+& r  .n   ",
"                      > @ 8 &.&.' & 8 c+% % h+b+y.b+k+x 8 &.a+' @ /.a+&.% 5+&.  ",
"                      : @ &.k.g a+g ' % % x Q b+b+b+k+% ' a+a+' @ ' a+g % ! &.  ",
"                      E.j+g k.k.k.&.@ % x c+r b+b+i+i+h+@ 8 a+' /.8 &.g x 3+&.  ",
"                      |.c+g g k.g a+c+Q x j+r i+i+k+i+k+x ' 8 8 ' 8 g k.x B+n   ",
"                      z+r a+g k.k.8 x h+% c+r b+i+k+i+b+h+j+' 8 ' 8 g k.c+u C   ",
"                      F.r x c+@ j+x r Q Q r Q Q Q Q Q Q Q r x % x c+c+@ j+x+    ",
"                      r./.@ % 4.T.j+8+S 8+@ 8+x U.I U.% % S @ @ j+j+x ~ s+1     ",
"                        ;+5 p W.< !.^.} J ^.E+c c %+p+X X %+s.c D !.-.; f+H .   ",
"                            0+. 0+0+0+..0+k.0+....k.0+0+k.k.k.0+0+. 0+. . . .   ",
"                        M.6 ; | h ^.J } } %+6.'.p+J c p ,+6 J } <.) y 7 r+,+0+  ",
"                      j.x j+r Q U.j+8+j+j+j+S x S j+j+u+r / @ j+c+x n+s+s+,+&.  ",
"                      W.n+n+/.' j+% Q h+t h+h+Q h+Q A+Q r h+r u+c+j+/./.x #.n   ",
"                      5 c+@ /./.g 8 j+r r r k+i+Q x % i+y.k+/.&.&.g k.g c+e+&.  ",
"                       +x /.@ /.g 8 @ % r r h+h+Q x x h+b+h+@ &.&.a+g k.c+#.n   ",
"                      n.c+/.j+' g 8 @ x r % h+h+r x c+Q b+k+j+& &.a+&.k.c+#.&.  ",
"                      {.x ' j+8 &.' j+% % r Q h+r c+j+x i+i+x a+&.a+&.g c+D+n   ",
"                      {.x 8 c+a+a+j+% r % r Q Q % c+@ j+k+b+r 8 g &.&.g c+u n   ",
"                      =+x ' j+&.8 c+r Q r Q h+Q % j+' @ Q b+Q 8 g &.g k.c+_.(   ",
"                      6 x j+@ @ x % r r r Q Q r r % x % r Q Q x j+j+j+@ j+3.    ",
"                      '.@ Q Q x c+j+j+j+j+j+j+j+j+j+j+j+j+c+c+j+c+% x % x f     ",
"                        M.b E.;+6+1 D 1 6+Y R R :+,+; i R r+w ; T J.^+w+<+      ",
"                                  . . .                                         ",
"                              . &.g 0+. . .                                     ",
"                            8.< H C H S.0+. .                                   ",
"                          1+ .r x c+' }.( . .                                   ",
"                        8.@ 8 /.n+r % @ ).( .                                   ",
"                      w c+i+' a+j+j+r r /.9 0+                                  ",
"                      h r i+' a+j+x x Q j+}.&.                                  ",
"                      i.Q i+' a+j+x r h+% }.n                                   ",
"                      %.$ r 8 8 j+% r h+Q +                                     ",
"                      %.4 x &.8 j+x r Q x 7                                     ",
"                      |.0 k+c+x x r h+k+: /+                                    ",
"                        g+h.b+r r r r -.;+0+. . . . . . . . . . . . . . . . .   ",
"                          A.W.e+#._+3 Z )+D.D.D.g g g g D.D...0+0+0+..g g D..   ",
"                      t.!+>.-.@+e+O t+C ].,.,.C =.n =.n C ].}.-.i *.'+C n } g   ",
"                      {.j+j+x r r r r % % % % % % r % r r r n+u+c+c+x % % 8+&.  ",
"                      1+@ /.&.' j+c+x r h+k+h+r % n+% % r % % k+b+y.b+A+r O &.  ",
"                      E.@ ' g a+' /.@ c+r Q r c+j+c+c+x c+@ @ % b+y.b+r r *.&.  ",
"                      E.@ 8 g &.' @ @ x Q Q x j+j+j+j+x x @ /.j+k+y.i+% r d+&.  ",
"                      >+j+a+g &.' @ c+r k+Q x @ @ @ j+c+x j+' /.Q b+i+x r e+n   ",
"                      d.j+a+g a+' @ x Q i+Q c+/.j+@ @ c+% x /.8 c+k+k+x r d+&.  ",
"                      0.x &.g a+' j+% h+k+Q j+@ j+j+j+x Q r /.a+/.r h+x r :+n   ",
"                      Z.i+&.g ' j+x Q k+i+k+% x % % % Q h+h+j+8 /.r k+r r >.    ",
"                      Z.y.x r r r r r % % % r % r r r % % % r r r r % % x t     ",
"                      N 7+7 D ].C C ,.} 6+6.,.].C C ` }.).,.].).,.].6.,.5+^     ",
"                                                                                ",
"                                          . . . . .               . .           ",
"                                      . ..)+g g D..               . . .         ",
"                                  n D } %+(.v.p } &.      K.e.t.1 ^.)+. .       ",
"                                * E.j j+j+c+c+j+*+8       L.0 #+r U.7.D.. .     ",
"                              = ] r Q i+b+y.y.% & a+        M >.n+c+5+'....     ",
"                          c .+n+x c+r k+y.P.y.r ].8           (.v.r x R ( . .   ",
"                          6.j+' ' @ r i+y.P.y.% a+C             T A+r c+).C .   ",
"                        e.Q 8 8 ' @ r i+P.y.y.r C 8               { $ k+*+J . . ",
"                        D x ' 8 ' @ % i+P.P.y.r & 8               a.%.$ c+k )+. ",
"                      <+t /.' ' ' @ r k+y.y.P.r ,.*+              F %.$+r =.k . ",
"                      l+h+% % % % r Q h+Q % Q r :+                  F+P.% 8 c . ",
"                      J.@ j+@ @ @ @ @ j+u+r u+% L                     e+c+@ D . ",
"                        8.= c p+E+s.s.p+(.< [ ) [ 0+. . . . . . . . o.i r j+v . ",
"                            . 0+0+. . 0+. 0+. 0+0+. . . . . . . . . k j h+c+<.. ",
"                        #.1 =.n =.=.C k 6.p h p+( C J 6 h h 6 s.h 4+< k+i+c+-.0+",
"                      q x u+c+c+c+c+j+j+c+c+c+j+j+j+j+j+c+c+j+j+c+c+U.y.b+r !   ",
"                      <+% % x x % r Q Q k+k+k+k+k+h+h+k+k+k+k+Q Q k+i+y.3.B p   ",
"                      ~+@ n+' ' ' /.j+x k+y.y.b+h+s+r h+b+b+h+c+c+k+P.y.% e+6.  ",
"                        =.r c+' ' /.j+x k+y.y.i+h+r % h+b+b+h+j+j+h+P.y.@ @+    ",
"                        k @ % /.' /.j+% k+y.b+i+Q % x r i+i+r j+j+h+y.Q ` /+    ",
"                          ( x % @ @ c+Q i+y.b+h+% j+@ % k+h+% j+c+k+y.s+$.      ",
"                            ].c+% % x Q i+y.y.h+x /./.% h+Q x c+x k+x m         ",
"                            6 k @ x Q k+b+y.b+Q c+' ' % k+Q % r Q j+c           ",
"                                ( ,.j+x r h+i+h+x ' ' r i+h+h+y.F /+            ",
"                            . . n ^.6 6+c+x c+% r r r % x c+x.u.b.              ",
"                            0+. .       j.> R }.*+` *+%+) V                     ",
"                      [+P !.} 1 .                                               ",
"                      1+x x 8 1 .                                               ",
"          . . . . . 0+i r % j+1 . . . . . . . . . . . . . . . . . . . . . . .   ",
"          *+8 ` 8 ` 1 7 r % c+9 ( ( y+y+o.)+)+S.=.n )+)+)+)+S.n )+)+)+)+)+)+.   ",
"    9.7 ;.> o+.+; k B+1.j+x c+=.S.=.n =.C c !.J ].} 6+f+f+4+k J !.@.+.F o '+)+  ",
"    r+ .x / x x % Q r h+@ c+r s+Q r s+r r % x % % x x c+x x % r x x j+j+j+t+S.  ",
"      H 8+x 8 & g @ Q r @ ' @ @ @ j+x % r i+b+b+i+y.y.b+b+i+h+k+i+b+b+k+c+,.S.  ",
"        p+% % 8 g 8 r % /.' 8 8 ' ' j+c+% k+i+i+b+b+b+i+k+k+Q Q h+b+y.y.x ` S.  ",
"          ;+s+x 8 8 x % /.8 8 8 ' ' j+% Q i+b+i+b+P.b+i+k+k+Q h+k+b+y.P.x ` S.  ",
"            ^+A+% j+j+c+/.' ' 8 8 ' j+% h+b+b+i+b+y.y.k+k+k+h+h+i+b+y.y.% ( o.  ",
"              , % % % j+/.' ' ' ' /.c+r h+i+b+i+y.y.y.k+h+k+h+h+k+b+b+b+r ,.S.  ",
"                6 /.% r @ ' 8 ' 8 /.j+% h+i+b+i+b+P.y.k+k+h+h+r h+k+k+i+% }.o.  ",
"                  q+u+% r /.' ' @ j+x r k+i+y.b+b+y.y.b+i+i+k+h+h+i+i+k+r t+    ",
"                    N % % x /.r r Q Q Q r r % % % c+c+x % % % r r r r r % O     ",
"                      ^ 8+% c+3+D =.].,.,.p+'.v.R #.+.e+,+v.(.= c c }.,.Y E.    ",
"                         +j+Q /+                                                ",
"                          D h+e.                                                ",
"                            J.                                                  "};
