#!/bin/bash

create_image() {

echo -n Merging image $no:

image=knob$no.png
mask=knob$no-mask.png
out=merge$no.png

cat > tmp.scm <<EOF
(let* (
(mask (car (file-png-load 1 "$mask" "$mask")))
(mask-drawable (car (gimp-image-active-drawable mask)))
(img (car (file-png-load 1 "$image" "$image")))
(img-drawable (car (gimp-image-active-drawable img)))
(color (car (gimp-image-pick-color img img-drawable 0 0 0 0 1)))
)
(gimp-fuzzy-select mask-drawable 0 0 0 0 FALSE 0 1 0)
(set! active-selection (car (gimp-selection-save mask)))
(gimp-selection-all img)
(gimp-edit-copy img-drawable)
(gimp-selection-all mask)
(set! mask-fs (car (gimp-edit-paste mask-drawable FALSE)))
(gimp-floating-sel-anchor mask-fs)
(gimp-selection-load active-selection)
(plug-in-colortoalpha 1 img mask-drawable color)
(gimp-image-crop mask 240 240 40 0)
(gimp-image-scale mask 42 42)
(file-png-save 1 mask mask-drawable "$out" "$out" 0 9 0 0 0 0 0)
(gimp-quit TRUE)
)
EOF

gimp -s -f -i -d --console-messages --batch '(load "tmp.scm" nil nil)'
rm tmp.scm

echo " done."

}

for no in {,1,2,3,4}{0,1,2,3,4,5,6,7,8,9}
do
	create_image;
done
