#!/usr/bin/python

import os, sys

def render(i, mask):
	angle = 280.0*float(i)/49.0+40.0-180.0
	
	inf = open('tX_knob.pov')
	outf = open('tmp.pov', 'w')
	for line in inf:
		out = line.replace('ROT_ANGLE','%lf' % angle)
		
		if mask:
			out = out.replace('BACKGROUND','Black')
			out = out.replace('MASKOPTION','no_shadow')
		else:
			out = out.replace('BACKGROUND','Blue')
			out = out.replace('MASKOPTION','')
		
		outf.write(out)
		
	outf.close()
	inf.close()
	
	os.system('/usr/local/share/povray-3.6/scripts/render_scene.sh tmp.pov')
	if mask:
		m = '-mask'
	else:
		m = ''
		
	os.rename('tmp.png', 'knob%0i%s.png' % (49-i,m))
	os.unlink('tmp.pov')


if len(sys.argv)>1:
	img = []
	for image in sys.argv[1:]:
		img.append(int(image))
else:
	img = xrange(0,50)
	
print img	

for i in img:
	render(i, False)
	render(i, True)
	
