/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "tX_glade_callbacks.h"
#include "tX_glade_interface.h"
#include "tX_glade_support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_tx_adjust (void)
{
  GtkWidget *tx_adjust;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox1;
  GtkWidget *label34;
  GtkWidget *table7;
  GtkObject *master_cycles_adj;
  GtkWidget *master_cycles;
  GtkWidget *label36;
  GtkWidget *label35;
  GtkObject *cycles_adj;
  GtkWidget *cycles;
  GtkWidget *create_event;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancel;
  GtkWidget *ok;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  tx_adjust = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tx_adjust), "Compute Pitch");

  dialog_vbox2 = GTK_DIALOG (tx_adjust)->vbox;
  gtk_widget_show (dialog_vbox2);

  vbox1 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 4);

  label34 = gtk_label_new ("In order to compute the optimum pitch value, please specify how many loops of this turntable should play as fast as how many loops of the masterturntable:");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (vbox1), label34, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label34), TRUE);

  table7 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table7);
  gtk_box_pack_start (GTK_BOX (vbox1), table7, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 3);

  master_cycles_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  master_cycles = gtk_spin_button_new (GTK_ADJUSTMENT (master_cycles_adj), 1, 0);
  gtk_widget_show (master_cycles);
  gtk_table_attach (GTK_TABLE (table7), master_cycles, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, master_cycles, "Specify the number of loops for the master turntable.", NULL);

  label36 = gtk_label_new ("Loops of the master turntable:");
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table7), label36, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_LEFT);

  label35 = gtk_label_new ("Loops of this turntable turntable:");
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table7), label35, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_LEFT);

  cycles_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  cycles = gtk_spin_button_new (GTK_ADJUSTMENT (cycles_adj), 1, 0);
  gtk_widget_show (cycles);
  gtk_table_attach (GTK_TABLE (table7), cycles, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cycles, "Specify the number of loops of _this_ turntable.", NULL);

  create_event = gtk_check_button_new_with_mnemonic ("Record a sequencer event");
  gtk_widget_show (create_event);
  gtk_box_pack_start (GTK_BOX (vbox1), create_event, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (create_event), TRUE);

  dialog_action_area2 = GTK_DIALOG (tx_adjust)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_adjust), cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);

  ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_adjust), ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tx_adjust, tx_adjust, "tx_adjust");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_adjust, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (tx_adjust, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (tx_adjust, label34, "label34");
  GLADE_HOOKUP_OBJECT (tx_adjust, table7, "table7");
  GLADE_HOOKUP_OBJECT (tx_adjust, master_cycles, "master_cycles");
  GLADE_HOOKUP_OBJECT (tx_adjust, label36, "label36");
  GLADE_HOOKUP_OBJECT (tx_adjust, label35, "label35");
  GLADE_HOOKUP_OBJECT (tx_adjust, cycles, "cycles");
  GLADE_HOOKUP_OBJECT (tx_adjust, create_event, "create_event");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_adjust, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (tx_adjust, cancel, "cancel");
  GLADE_HOOKUP_OBJECT (tx_adjust, ok, "ok");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_adjust, tooltips, "tooltips");

  return tx_adjust;
}

GtkWidget*
create_tx_options (void)
{
  GtkWidget *tx_options;
  GtkWidget *dialog_vbox3;
  GtkWidget *notebook1;
  GtkWidget *table4;
  GtkWidget *label18;
  GtkWidget *hbox2;
  GtkWidget *oss_driver;
  GSList *oss_driver_group = NULL;
  GtkWidget *alsa_driver;
  GtkWidget *jack_driver;
  GtkWidget *use_realtime_label;
  GtkWidget *use_realtime;
  GtkWidget *label1;
  GtkWidget *table5;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *oss_audio_device;
  GtkWidget *combo_entry2;
  GtkObject *oss_buffers_adj;
  GtkWidget *oss_buffers;
  GtkWidget *oss_buffersize;
  GtkWidget *oss_samplerate;
  GtkWidget *combo_entry3;
  GtkWidget *label15;
  GtkWidget *table6;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *alsa_audio_device;
  GtkWidget *combo_entry4;
  GtkWidget *alsa_samplerate;
  GtkWidget *combo_entry5;
  GtkWidget *alsa_period_time;
  GtkWidget *label32;
  GtkWidget *alsa_buffer_time;
  GtkWidget *label39;
  GtkWidget *alsa_free_hwstats;
  GtkWidget *label16;
  GtkWidget *table1;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *xinput_device;
  GtkWidget *combo_entry1;
  GtkWidget *mouse_speed;
  GtkWidget *stop_sense_cycles;
  GtkWidget *label25;
  GtkWidget *xinput_enable;
  GtkWidget *label37;
  GtkWidget *vtt_inertia;
  GtkWidget *label4;
  GtkWidget *table2;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *mainwin_tooltips;
  GtkWidget *update_idle;
  GtkWidget *update_delay;
  GtkWidget *vumeter_decay;
  GtkWidget *label14;
  GtkWidget *startup_nagbox;
  GtkWidget *label12;
  GtkWidget *hbox1;
  GtkWidget *buttons_text_and_icon;
  GSList *buttons_text_and_icon_group = NULL;
  GtkWidget *buttons_icon_only;
  GtkWidget *buttons_text_only;
  GtkWidget *label38;
  GtkObject *filename_length_adj;
  GtkWidget *filename_length;
  GtkWidget *label2;
  GtkWidget *table8;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *wav_display_bg_focus;
  GtkWidget *wav_display_bg_no_focus;
  GtkWidget *wav_display_fg_focus;
  GtkWidget *wav_display_fg_no_focus;
  GtkWidget *wav_display_cursor;
  GtkWidget *wav_display_cursor_mute;
  GtkWidget *label41;
  GtkWidget *table9;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *vu_meter_border_intensity;
  GtkWidget *vu_meter_bg;
  GtkWidget *vu_meter_normal;
  GtkWidget *vu_meter_loud;
  GtkWidget *label52;
  GtkWidget *table3;
  GtkWidget *label13;
  GtkWidget *soundfile_editor;
  GtkWidget *label26;
  GtkWidget *prelisten_enabled;
  GtkWidget *label31;
  GtkWidget *ladspa_rdf_path;
  GtkWidget *label33;
  GtkWidget *compress_set_files;
  GtkWidget *label40;
  GtkWidget *reconnect_enabled;
  GtkWidget *label57;
  GtkWidget *quit_confirm;
  GtkWidget *label3;
  GtkWidget *dialog_action_area3;
  GtkWidget *pref_reset;
  GtkWidget *pref_cancel;
  GtkWidget *pref_apply;
  GtkWidget *pref_ok;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  tx_options = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tx_options), "terminatorX Preferences");

  dialog_vbox3 = GTK_DIALOG (tx_options)->vbox;
  gtk_widget_show (dialog_vbox3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), notebook1, TRUE, TRUE, 0);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (notebook1), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 2);

  label18 = gtk_label_new ("Use Driver:");
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table4), label18, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table4), hbox2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  oss_driver = gtk_radio_button_new_with_mnemonic (NULL, "OSS");
  gtk_widget_show (oss_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), oss_driver, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, oss_driver, "Use the OSS (Open Sound System) driver for audio output.", NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (oss_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (oss_driver));

  alsa_driver = gtk_radio_button_new_with_mnemonic (NULL, "ALSA");
  gtk_widget_show (alsa_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), alsa_driver, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, alsa_driver, "Use the ALSA (Advanced Linux Sound System) driver for audio output.", NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (alsa_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (alsa_driver));

  jack_driver = gtk_radio_button_new_with_mnemonic (NULL, "JACK");
  gtk_widget_show (jack_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), jack_driver, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, jack_driver, "Use the JACK (JACK Audio Connection Kit) driver for audio output.", NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (jack_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (jack_driver));

  use_realtime_label = gtk_label_new ("Use realtime scheduling\nwhere available:");
  gtk_widget_show (use_realtime_label);
  gtk_table_attach (GTK_TABLE (table4), use_realtime_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (use_realtime_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (use_realtime_label), 0, 0.5);

  use_realtime = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (use_realtime);
  gtk_table_attach (GTK_TABLE (table4), use_realtime, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label1 = gtk_label_new ("Audio");
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (notebook1), table5);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 2);

  label21 = gtk_label_new ("Audio Device:");
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table5), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new ("No. of Buffers:");
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table5), label22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new ("Buffersize (2^x):");
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table5), label23, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new ("Samplerate (Hz):");
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table5), label24, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  oss_audio_device = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (oss_audio_device)->popwin),
                     "GladeParentKey", oss_audio_device);
  gtk_widget_show (oss_audio_device);
  gtk_table_attach (GTK_TABLE (table5), oss_audio_device, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = GTK_COMBO (oss_audio_device)->entry;
  gtk_widget_show (combo_entry2);
  gtk_tooltips_set_tip (tooltips, combo_entry2, "Select the audiodevice you want terminatorX to send its output to.", NULL);

  oss_buffers_adj = gtk_adjustment_new (2, 2, 5, 1, 10, 10);
  oss_buffers = gtk_spin_button_new (GTK_ADJUSTMENT (oss_buffers_adj), 1, 0);
  gtk_widget_show (oss_buffers);
  gtk_table_attach (GTK_TABLE (table5), oss_buffers, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, oss_buffers, "Sets the number of kernel level audio buffers. Actually most systems should run just fine with two.", NULL);

  oss_buffersize = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (9, 8, 16, 1, 1, 1)));
  gtk_widget_show (oss_buffersize);
  gtk_table_attach (GTK_TABLE (table5), oss_buffersize, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (oss_buffersize), 0);

  oss_samplerate = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (oss_samplerate)->popwin),
                     "GladeParentKey", oss_samplerate);
  gtk_widget_show (oss_samplerate);
  gtk_table_attach (GTK_TABLE (table5), oss_samplerate, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry3 = GTK_COMBO (oss_samplerate)->entry;
  gtk_widget_show (combo_entry3);
  gtk_tooltips_set_tip (tooltips, combo_entry3, "Select the sampling to use for this audio device - the higher the better quality. Note that not all sampling rates are supported by all audio devices.", NULL);

  label15 = gtk_label_new ("Audio: OSS");
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  table6 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (notebook1), table6);
  gtk_container_set_border_width (GTK_CONTAINER (table6), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 2);

  label27 = gtk_label_new ("Audio Device:");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table6), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label29 = gtk_label_new ("Period Time (ms):");
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table6), label29, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new ("Samplerate (Hz):");
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table6), label30, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  alsa_audio_device = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (alsa_audio_device)->popwin),
                     "GladeParentKey", alsa_audio_device);
  gtk_widget_show (alsa_audio_device);
  gtk_table_attach (GTK_TABLE (table6), alsa_audio_device, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry4 = GTK_COMBO (alsa_audio_device)->entry;
  gtk_widget_show (combo_entry4);

  alsa_samplerate = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (alsa_samplerate)->popwin),
                     "GladeParentKey", alsa_samplerate);
  gtk_widget_show (alsa_samplerate);
  gtk_table_attach (GTK_TABLE (table6), alsa_samplerate, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry5 = GTK_COMBO (alsa_samplerate)->entry;
  gtk_widget_show (combo_entry5);

  alsa_period_time = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (29, 10, 500, 1, 10, 10)));
  gtk_widget_show (alsa_period_time);
  gtk_table_attach (GTK_TABLE (table6), alsa_period_time, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (alsa_period_time), 0);

  label32 = gtk_label_new ("Buffer Time (ms):");
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table6), label32, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  alsa_buffer_time = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (50, 10, 500, 1, 10, 10)));
  gtk_widget_show (alsa_buffer_time);
  gtk_table_attach (GTK_TABLE (table6), alsa_buffer_time, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (alsa_buffer_time), 0);

  label39 = gtk_label_new ("Free HWstats:");
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table6), label39, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  alsa_free_hwstats = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (alsa_free_hwstats);
  gtk_table_attach (GTK_TABLE (table6), alsa_free_hwstats, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (alsa_free_hwstats), TRUE);

  label16 = gtk_label_new ("Audio: ALSA");
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  label5 = gtk_label_new ("XInput Device:");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new ("Mouse Speed:");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new ("Stop-Sense-Cycles:");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  xinput_device = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (xinput_device)->popwin),
                     "GladeParentKey", xinput_device);
  gtk_widget_show (xinput_device);
  gtk_table_attach (GTK_TABLE (table1), xinput_device, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry1 = GTK_COMBO (xinput_device)->entry;
  gtk_widget_show (combo_entry1);
  gtk_tooltips_set_tip (tooltips, combo_entry1, "Select the input device to use when XInput is enabled. Note: do not use this option if you plan on using your default device (standard mouse).", NULL);

  mouse_speed = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -10, 10, 0.5, 0.1, 0.1)));
  gtk_widget_show (mouse_speed);
  gtk_table_attach (GTK_TABLE (table1), mouse_speed, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  stop_sense_cycles = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (80, 30, 250, 5, 1, 1)));
  gtk_widget_show (stop_sense_cycles);
  gtk_table_attach (GTK_TABLE (table1), stop_sense_cycles, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (stop_sense_cycles), 0);

  label25 = gtk_label_new ("XInput:");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table1), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  xinput_enable = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (xinput_enable);
  gtk_table_attach (GTK_TABLE (table1), xinput_enable, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, xinput_enable, "CAREFUL! Enable this *only* if you want to use an input device than your default X-Pointer (yes, your mouse ;). You have to select your desired device as well. Selecting the default mouse pointer will crash terminatorX so if you want to use that keep this option disabled.", NULL);

  label37 = gtk_label_new ("Turntable Inertia:");
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table1), label37, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  vtt_inertia = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 1, 310, 0.01, 1, 10)));
  gtk_widget_show (vtt_inertia);
  gtk_table_attach (GTK_TABLE (table1), vtt_inertia, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label4 = gtk_label_new ("Input");
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  table2 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  label8 = gtk_label_new ("Main Window Tooltips:");
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table2), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  label9 = gtk_label_new ("Update Idle (ms):");
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  label10 = gtk_label_new ("Update Delay (cycles):");
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new ("VU Meter Decay:");
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  mainwin_tooltips = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (mainwin_tooltips);
  gtk_table_attach (GTK_TABLE (table2), mainwin_tooltips, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, mainwin_tooltips, "Enable tooltips for the terminatorX main window.", NULL);

  update_idle = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (11, 2, 100, 1, 10, 10)));
  gtk_widget_show (update_idle);
  gtk_table_attach (GTK_TABLE (table2), update_idle, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (update_idle), 0);

  update_delay = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 15, 1, 10, 10)));
  gtk_widget_show (update_delay);
  gtk_table_attach (GTK_TABLE (table2), update_delay, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (update_delay), 0);

  vumeter_decay = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.8, 0.8, 0.99, 0.01, 0.01, 0.001)));
  gtk_widget_show (vumeter_decay);
  gtk_table_attach (GTK_TABLE (table2), vumeter_decay, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label14 = gtk_label_new ("Startup-Nagbox:");
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  startup_nagbox = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (startup_nagbox);
  gtk_table_attach (GTK_TABLE (table2), startup_nagbox, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, startup_nagbox, "Display nagbox on startup while loading data.", NULL);

  label12 = gtk_label_new ("Buttons:");
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  hbox1 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table2), hbox1, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  buttons_text_and_icon = gtk_radio_button_new_with_mnemonic (NULL, "Text + Icon");
  gtk_widget_show (buttons_text_and_icon);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_text_and_icon, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_text_and_icon), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_text_and_icon));

  buttons_icon_only = gtk_radio_button_new_with_mnemonic (NULL, "Icon Only");
  gtk_widget_show (buttons_icon_only);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_icon_only, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_icon_only), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_icon_only));

  buttons_text_only = gtk_radio_button_new_with_mnemonic (NULL, "Text Only");
  gtk_widget_show (buttons_text_only);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_text_only, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_text_only), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_text_only));

  label38 = gtk_label_new ("Filename Length:");
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table2), label38, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  filename_length_adj = gtk_adjustment_new (8, 3, 255, 1, 10, 10);
  filename_length = gtk_spin_button_new (GTK_ADJUSTMENT (filename_length_adj), 1, 0);
  gtk_widget_show (filename_length);
  gtk_table_attach (GTK_TABLE (table2), filename_length, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label2 = gtk_label_new ("User Interface");
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label2);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  table8 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (notebook1), table8);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 2);

  label42 = gtk_label_new ("Background (focus):");
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table8), label42, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label42), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new ("Background (no focus):");
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table8), label43, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label43), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label44 = gtk_label_new ("Signal (focus):");
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table8), label44, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new ("Signal (no focus):");
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table8), label45, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label45), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  label46 = gtk_label_new ("Cursor:");
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table8), label46, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  label47 = gtk_label_new ("Cursor (mute):");
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table8), label47, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  wav_display_bg_focus = gtk_button_new_with_mnemonic ("button1");
  gtk_widget_show (wav_display_bg_focus);
  gtk_table_attach (GTK_TABLE (table8), wav_display_bg_focus, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  wav_display_bg_no_focus = gtk_button_new_with_mnemonic ("button2");
  gtk_widget_show (wav_display_bg_no_focus);
  gtk_table_attach (GTK_TABLE (table8), wav_display_bg_no_focus, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  wav_display_fg_focus = gtk_button_new_with_mnemonic ("button3");
  gtk_widget_show (wav_display_fg_focus);
  gtk_table_attach (GTK_TABLE (table8), wav_display_fg_focus, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  wav_display_fg_no_focus = gtk_button_new_with_mnemonic ("button4");
  gtk_widget_show (wav_display_fg_no_focus);
  gtk_table_attach (GTK_TABLE (table8), wav_display_fg_no_focus, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  wav_display_cursor = gtk_button_new_with_mnemonic ("button5");
  gtk_widget_show (wav_display_cursor);
  gtk_table_attach (GTK_TABLE (table8), wav_display_cursor, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  wav_display_cursor_mute = gtk_button_new_with_mnemonic ("button6");
  gtk_widget_show (wav_display_cursor_mute);
  gtk_table_attach (GTK_TABLE (table8), wav_display_cursor_mute, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label41 = gtk_label_new ("Audio Colors");
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label41);
  gtk_label_set_justify (GTK_LABEL (label41), GTK_JUSTIFY_LEFT);

  table9 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (notebook1), table9);
  gtk_container_set_border_width (GTK_CONTAINER (table9), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table9), 2);

  label53 = gtk_label_new ("Background:");
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table9), label53, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label53), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label54 = gtk_label_new ("Regular Signal:");
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table9), label54, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label54), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  label55 = gtk_label_new ("Loud Signal:");
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table9), label55, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label55), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label55), 0, 0.5);

  label56 = gtk_label_new ("Scale Opacity:");
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table9), label56, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label56), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);

  vu_meter_border_intensity = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.07, 0, 1, 0.01, 0, 0)));
  gtk_widget_show (vu_meter_border_intensity);
  gtk_table_attach (GTK_TABLE (table9), vu_meter_border_intensity, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_value_pos (GTK_SCALE (vu_meter_border_intensity), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (vu_meter_border_intensity), 2);

  vu_meter_bg = gtk_button_new_with_mnemonic ("button7");
  gtk_widget_show (vu_meter_bg);
  gtk_table_attach (GTK_TABLE (table9), vu_meter_bg, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  vu_meter_normal = gtk_button_new_with_mnemonic ("button8");
  gtk_widget_show (vu_meter_normal);
  gtk_table_attach (GTK_TABLE (table9), vu_meter_normal, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  vu_meter_loud = gtk_button_new_with_mnemonic ("button9");
  gtk_widget_show (vu_meter_loud);
  gtk_table_attach (GTK_TABLE (table9), vu_meter_loud, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label52 = gtk_label_new ("VU Colors");
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label52);
  gtk_label_set_justify (GTK_LABEL (label52), GTK_JUSTIFY_LEFT);

  table3 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (notebook1), table3);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 2);

  label13 = gtk_label_new ("Soundfile Editor:");
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table3), label13, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  soundfile_editor = gtk_entry_new ();
  gtk_widget_show (soundfile_editor);
  gtk_table_attach (GTK_TABLE (table3), soundfile_editor, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, soundfile_editor, "Enter the command to run your favourite soundfile editor. It will be started when you choose \"Edit File\" from the turntable's file menu.", NULL);

  label26 = gtk_label_new ("\"Pre-Listen\" to soundfiles:");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table3), label26, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  prelisten_enabled = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (prelisten_enabled);
  gtk_table_attach (GTK_TABLE (table3), prelisten_enabled, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, prelisten_enabled, "When enabled soundfiles will be playedback when selected in a file dialog (before loading them).", NULL);

  label31 = gtk_label_new ("LADSPA RDF Path:");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table3), label31, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  ladspa_rdf_path = gtk_entry_new ();
  gtk_widget_show (ladspa_rdf_path);
  gtk_table_attach (GTK_TABLE (table3), ladspa_rdf_path, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label33 = gtk_label_new ("Compress set files:");
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table3), label33, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  compress_set_files = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (compress_set_files);
  gtk_table_attach (GTK_TABLE (table3), compress_set_files, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label40 = gtk_label_new ("Restore MIDI connections:");
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table3), label40, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  reconnect_enabled = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (reconnect_enabled);
  gtk_table_attach (GTK_TABLE (table3), reconnect_enabled, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, reconnect_enabled, "When enabled soundfiles will be playedback when selected in a file dialog (before loading them).", NULL);

  label57 = gtk_label_new ("Ask for \"Quit\" confirmation:");
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table3), label57, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label57), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label57), 0, 0.5);

  quit_confirm = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (quit_confirm);
  gtk_table_attach (GTK_TABLE (table3), quit_confirm, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new ("Misc");
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 7), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  dialog_action_area3 = GTK_DIALOG (tx_options)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  pref_reset = gtk_button_new_from_stock ("gtk-revert-to-saved");
  gtk_widget_show (pref_reset);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_reset, 0);
  GTK_WIDGET_SET_FLAGS (pref_reset, GTK_CAN_DEFAULT);

  pref_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (pref_cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (pref_cancel, GTK_CAN_DEFAULT);

  pref_apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (pref_apply);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_apply, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (pref_apply, GTK_CAN_DEFAULT);

  pref_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (pref_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (pref_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) tx_options, "destroy",
                    G_CALLBACK (on_tx_options_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) alsa_buffer_time, "value_changed",
                            G_CALLBACK (on_alsa_buffer_time_value_changed),
                            GTK_OBJECT (alsa_period_time));
  g_signal_connect_swapped ((gpointer) wav_display_bg_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_bg_focus));
  g_signal_connect_swapped ((gpointer) wav_display_bg_no_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_bg_no_focus));
  g_signal_connect_swapped ((gpointer) wav_display_fg_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_fg_focus));
  g_signal_connect_swapped ((gpointer) wav_display_fg_no_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_fg_no_focus));
  g_signal_connect_swapped ((gpointer) wav_display_cursor, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_cursor));
  g_signal_connect_swapped ((gpointer) wav_display_cursor_mute, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (wav_display_cursor_mute));
  g_signal_connect_swapped ((gpointer) vu_meter_bg, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (vu_meter_bg));
  g_signal_connect_swapped ((gpointer) vu_meter_normal, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (vu_meter_normal));
  g_signal_connect_swapped ((gpointer) vu_meter_loud, "clicked",
                            G_CALLBACK (color_clicked),
                            GTK_OBJECT (vu_meter_loud));
  g_signal_connect ((gpointer) pref_reset, "clicked",
                    G_CALLBACK (on_pref_reset_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_cancel, "clicked",
                    G_CALLBACK (on_pref_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_apply, "clicked",
                    G_CALLBACK (on_pref_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_ok, "clicked",
                    G_CALLBACK (on_pref_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tx_options, tx_options, "tx_options");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_options, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (tx_options, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (tx_options, table4, "table4");
  GLADE_HOOKUP_OBJECT (tx_options, label18, "label18");
  GLADE_HOOKUP_OBJECT (tx_options, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (tx_options, oss_driver, "oss_driver");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_driver, "alsa_driver");
  GLADE_HOOKUP_OBJECT (tx_options, jack_driver, "jack_driver");
  GLADE_HOOKUP_OBJECT (tx_options, use_realtime_label, "use_realtime_label");
  GLADE_HOOKUP_OBJECT (tx_options, use_realtime, "use_realtime");
  GLADE_HOOKUP_OBJECT (tx_options, label1, "label1");
  GLADE_HOOKUP_OBJECT (tx_options, table5, "table5");
  GLADE_HOOKUP_OBJECT (tx_options, label21, "label21");
  GLADE_HOOKUP_OBJECT (tx_options, label22, "label22");
  GLADE_HOOKUP_OBJECT (tx_options, label23, "label23");
  GLADE_HOOKUP_OBJECT (tx_options, label24, "label24");
  GLADE_HOOKUP_OBJECT (tx_options, oss_audio_device, "oss_audio_device");
  GLADE_HOOKUP_OBJECT (tx_options, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (tx_options, oss_buffers, "oss_buffers");
  GLADE_HOOKUP_OBJECT (tx_options, oss_buffersize, "oss_buffersize");
  GLADE_HOOKUP_OBJECT (tx_options, oss_samplerate, "oss_samplerate");
  GLADE_HOOKUP_OBJECT (tx_options, combo_entry3, "combo_entry3");
  GLADE_HOOKUP_OBJECT (tx_options, label15, "label15");
  GLADE_HOOKUP_OBJECT (tx_options, table6, "table6");
  GLADE_HOOKUP_OBJECT (tx_options, label27, "label27");
  GLADE_HOOKUP_OBJECT (tx_options, label29, "label29");
  GLADE_HOOKUP_OBJECT (tx_options, label30, "label30");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_audio_device, "alsa_audio_device");
  GLADE_HOOKUP_OBJECT (tx_options, combo_entry4, "combo_entry4");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_samplerate, "alsa_samplerate");
  GLADE_HOOKUP_OBJECT (tx_options, combo_entry5, "combo_entry5");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_period_time, "alsa_period_time");
  GLADE_HOOKUP_OBJECT (tx_options, label32, "label32");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_buffer_time, "alsa_buffer_time");
  GLADE_HOOKUP_OBJECT (tx_options, label39, "label39");
  GLADE_HOOKUP_OBJECT (tx_options, alsa_free_hwstats, "alsa_free_hwstats");
  GLADE_HOOKUP_OBJECT (tx_options, label16, "label16");
  GLADE_HOOKUP_OBJECT (tx_options, table1, "table1");
  GLADE_HOOKUP_OBJECT (tx_options, label5, "label5");
  GLADE_HOOKUP_OBJECT (tx_options, label6, "label6");
  GLADE_HOOKUP_OBJECT (tx_options, label7, "label7");
  GLADE_HOOKUP_OBJECT (tx_options, xinput_device, "xinput_device");
  GLADE_HOOKUP_OBJECT (tx_options, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (tx_options, mouse_speed, "mouse_speed");
  GLADE_HOOKUP_OBJECT (tx_options, stop_sense_cycles, "stop_sense_cycles");
  GLADE_HOOKUP_OBJECT (tx_options, label25, "label25");
  GLADE_HOOKUP_OBJECT (tx_options, xinput_enable, "xinput_enable");
  GLADE_HOOKUP_OBJECT (tx_options, label37, "label37");
  GLADE_HOOKUP_OBJECT (tx_options, vtt_inertia, "vtt_inertia");
  GLADE_HOOKUP_OBJECT (tx_options, label4, "label4");
  GLADE_HOOKUP_OBJECT (tx_options, table2, "table2");
  GLADE_HOOKUP_OBJECT (tx_options, label8, "label8");
  GLADE_HOOKUP_OBJECT (tx_options, label9, "label9");
  GLADE_HOOKUP_OBJECT (tx_options, label10, "label10");
  GLADE_HOOKUP_OBJECT (tx_options, label11, "label11");
  GLADE_HOOKUP_OBJECT (tx_options, mainwin_tooltips, "mainwin_tooltips");
  GLADE_HOOKUP_OBJECT (tx_options, update_idle, "update_idle");
  GLADE_HOOKUP_OBJECT (tx_options, update_delay, "update_delay");
  GLADE_HOOKUP_OBJECT (tx_options, vumeter_decay, "vumeter_decay");
  GLADE_HOOKUP_OBJECT (tx_options, label14, "label14");
  GLADE_HOOKUP_OBJECT (tx_options, startup_nagbox, "startup_nagbox");
  GLADE_HOOKUP_OBJECT (tx_options, label12, "label12");
  GLADE_HOOKUP_OBJECT (tx_options, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (tx_options, buttons_text_and_icon, "buttons_text_and_icon");
  GLADE_HOOKUP_OBJECT (tx_options, buttons_icon_only, "buttons_icon_only");
  GLADE_HOOKUP_OBJECT (tx_options, buttons_text_only, "buttons_text_only");
  GLADE_HOOKUP_OBJECT (tx_options, label38, "label38");
  GLADE_HOOKUP_OBJECT (tx_options, filename_length, "filename_length");
  GLADE_HOOKUP_OBJECT (tx_options, label2, "label2");
  GLADE_HOOKUP_OBJECT (tx_options, table8, "table8");
  GLADE_HOOKUP_OBJECT (tx_options, label42, "label42");
  GLADE_HOOKUP_OBJECT (tx_options, label43, "label43");
  GLADE_HOOKUP_OBJECT (tx_options, label44, "label44");
  GLADE_HOOKUP_OBJECT (tx_options, label45, "label45");
  GLADE_HOOKUP_OBJECT (tx_options, label46, "label46");
  GLADE_HOOKUP_OBJECT (tx_options, label47, "label47");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_bg_focus, "wav_display_bg_focus");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_bg_no_focus, "wav_display_bg_no_focus");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_fg_focus, "wav_display_fg_focus");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_fg_no_focus, "wav_display_fg_no_focus");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_cursor, "wav_display_cursor");
  GLADE_HOOKUP_OBJECT (tx_options, wav_display_cursor_mute, "wav_display_cursor_mute");
  GLADE_HOOKUP_OBJECT (tx_options, label41, "label41");
  GLADE_HOOKUP_OBJECT (tx_options, table9, "table9");
  GLADE_HOOKUP_OBJECT (tx_options, label53, "label53");
  GLADE_HOOKUP_OBJECT (tx_options, label54, "label54");
  GLADE_HOOKUP_OBJECT (tx_options, label55, "label55");
  GLADE_HOOKUP_OBJECT (tx_options, label56, "label56");
  GLADE_HOOKUP_OBJECT (tx_options, vu_meter_border_intensity, "vu_meter_border_intensity");
  GLADE_HOOKUP_OBJECT (tx_options, vu_meter_bg, "vu_meter_bg");
  GLADE_HOOKUP_OBJECT (tx_options, vu_meter_normal, "vu_meter_normal");
  GLADE_HOOKUP_OBJECT (tx_options, vu_meter_loud, "vu_meter_loud");
  GLADE_HOOKUP_OBJECT (tx_options, label52, "label52");
  GLADE_HOOKUP_OBJECT (tx_options, table3, "table3");
  GLADE_HOOKUP_OBJECT (tx_options, label13, "label13");
  GLADE_HOOKUP_OBJECT (tx_options, soundfile_editor, "soundfile_editor");
  GLADE_HOOKUP_OBJECT (tx_options, label26, "label26");
  GLADE_HOOKUP_OBJECT (tx_options, prelisten_enabled, "prelisten_enabled");
  GLADE_HOOKUP_OBJECT (tx_options, label31, "label31");
  GLADE_HOOKUP_OBJECT (tx_options, ladspa_rdf_path, "ladspa_rdf_path");
  GLADE_HOOKUP_OBJECT (tx_options, label33, "label33");
  GLADE_HOOKUP_OBJECT (tx_options, compress_set_files, "compress_set_files");
  GLADE_HOOKUP_OBJECT (tx_options, label40, "label40");
  GLADE_HOOKUP_OBJECT (tx_options, reconnect_enabled, "reconnect_enabled");
  GLADE_HOOKUP_OBJECT (tx_options, label57, "label57");
  GLADE_HOOKUP_OBJECT (tx_options, quit_confirm, "quit_confirm");
  GLADE_HOOKUP_OBJECT (tx_options, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_options, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (tx_options, pref_reset, "pref_reset");
  GLADE_HOOKUP_OBJECT (tx_options, pref_cancel, "pref_cancel");
  GLADE_HOOKUP_OBJECT (tx_options, pref_apply, "pref_apply");
  GLADE_HOOKUP_OBJECT (tx_options, pref_ok, "pref_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_options, tooltips, "tooltips");

  return tx_options;
}

GtkWidget*
create_tx_del_mode (void)
{
  GtkWidget *tx_del_mode;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox2;
  GtkWidget *delmode_label;
  GtkWidget *hbox3;
  GtkWidget *vbox3;
  GtkWidget *all_events;
  GSList *all_events_group = NULL;
  GtkWidget *upto_current;
  GtkWidget *from_current;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  tx_del_mode = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tx_del_mode), "Choose Events to Delete");

  dialog_vbox4 = GTK_DIALOG (tx_del_mode)->vbox;
  gtk_widget_show (dialog_vbox4);

  vbox2 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 4);

  delmode_label = gtk_label_new ("Select which events to delete.");
  gtk_widget_show (delmode_label);
  gtk_box_pack_start (GTK_BOX (vbox2), delmode_label, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (delmode_label), GTK_JUSTIFY_LEFT);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, TRUE, FALSE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox3, TRUE, FALSE, 0);

  all_events = gtk_radio_button_new_with_mnemonic (NULL, "Complete song");
  gtk_widget_show (all_events);
  gtk_box_pack_start (GTK_BOX (vbox3), all_events, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (all_events), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (all_events));

  upto_current = gtk_radio_button_new_with_mnemonic (NULL, "Upto the current song position");
  gtk_widget_show (upto_current);
  gtk_box_pack_start (GTK_BOX (vbox3), upto_current, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (upto_current), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (upto_current));

  from_current = gtk_radio_button_new_with_mnemonic (NULL, "From the current song position");
  gtk_widget_show (from_current);
  gtk_box_pack_start (GTK_BOX (vbox3), from_current, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (from_current), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (from_current));

  dialog_action_area4 = GTK_DIALOG (tx_del_mode)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_del_mode), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_del_mode), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_del_mode_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_del_mode_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tx_del_mode, tx_del_mode, "tx_del_mode");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_del_mode, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (tx_del_mode, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (tx_del_mode, delmode_label, "delmode_label");
  GLADE_HOOKUP_OBJECT (tx_del_mode, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (tx_del_mode, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (tx_del_mode, all_events, "all_events");
  GLADE_HOOKUP_OBJECT (tx_del_mode, upto_current, "upto_current");
  GLADE_HOOKUP_OBJECT (tx_del_mode, from_current, "from_current");
  GLADE_HOOKUP_OBJECT_NO_REF (tx_del_mode, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (tx_del_mode, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (tx_del_mode, okbutton1, "okbutton1");

  return tx_del_mode;
}

GtkWidget*
create_tX_midilearn (void)
{
  GtkWidget *tX_midilearn;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox4;
  GtkWidget *midilabel;
  GtkWidget *dialog_action_area5;
  GtkWidget *cancel;

  tX_midilearn = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tX_midilearn), "MIDI Learn");

  dialog_vbox5 = GTK_DIALOG (tX_midilearn)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 4);

  midilabel = gtk_label_new ("Waiting for MIDI event....");
  gtk_widget_show (midilabel);
  gtk_box_pack_start (GTK_BOX (vbox4), midilabel, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (midilabel), GTK_JUSTIFY_LEFT);

  dialog_action_area5 = GTK_DIALOG (tX_midilearn)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tX_midilearn), cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tX_midilearn, tX_midilearn, "tX_midilearn");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_midilearn, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (tX_midilearn, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (tX_midilearn, midilabel, "midilabel");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_midilearn, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (tX_midilearn, cancel, "cancel");

  return tX_midilearn;
}

GtkWidget*
create_tX_color_selection (void)
{
  GtkWidget *tX_color_selection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkWidget *help_button1;
  GtkWidget *color_selection;

  tX_color_selection = gtk_color_selection_dialog_new ("Select Color");
  gtk_window_set_resizable (GTK_WINDOW (tX_color_selection), FALSE);

  ok_button1 = GTK_COLOR_SELECTION_DIALOG (tX_color_selection)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_COLOR_SELECTION_DIALOG (tX_color_selection)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  help_button1 = GTK_COLOR_SELECTION_DIALOG (tX_color_selection)->help_button;
  gtk_widget_show (help_button1);
  GTK_WIDGET_SET_FLAGS (help_button1, GTK_CAN_DEFAULT);

  color_selection = GTK_COLOR_SELECTION_DIALOG (tX_color_selection)->colorsel;
  gtk_widget_show (color_selection);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (color_selection), FALSE);

  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (on_color_selection_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_color_selection_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tX_color_selection, tX_color_selection, "tX_color_selection");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_color_selection, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_color_selection, cancel_button1, "cancel_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_color_selection, help_button1, "help_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (tX_color_selection, color_selection, "color_selection");

  return tX_color_selection;
}

