/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_tx_adjust (void);
GtkWidget* create_tx_options (void);
GtkWidget* create_tx_del_mode (void);
GtkWidget* create_tX_midilearn (void);
GtkWidget* create_tX_color_selection (void);
