/*
 * This file is no longer being generated by Glade and contains hand 
 * crafted code.
 */


#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gtk/gtk.h>

#include "tX_ui_callbacks.h"
#include "tX_ui_interface.h"
#include "tX_ui_support.h"

#define TX_UI_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    g_object_ref (widget), (GDestroyNotify) g_object_unref)

#define TX_UI_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_tx_adjust (void)
{
  GtkWidget *tx_adjust;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox1;
  GtkWidget *label34;
  GtkWidget *grid7;
  GtkAdjustment *master_cycles_adj;
  GtkWidget *master_cycles;
  GtkWidget *label36;
  GtkWidget *label35;
  GtkAdjustment *cycles_adj;
  GtkWidget *cycles;
  GtkWidget *create_event;
  GtkWidget *cancel;
  GtkWidget *ok;
  
  tx_adjust = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tx_adjust), "Compute Pitch");

  dialog_vbox2 = gtk_dialog_get_content_area(GTK_DIALOG (tx_adjust));
  gtk_widget_show (dialog_vbox2);

  vbox1 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 4);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 4);

  label34 = gtk_label_new ("In order to compute the optimum pitch value, please specify how many loops of this turntable should play as fast as how many loops of the masterturntable:");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (vbox1), label34, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label34), TRUE);

  grid7 = gtk_grid_new ();
  gtk_widget_show (grid7);
  gtk_box_pack_start (GTK_BOX (vbox1), grid7, TRUE, TRUE, 0);
  gtk_grid_set_column_spacing (GTK_GRID (grid7), 3);

  master_cycles_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 0);
  master_cycles = gtk_spin_button_new (GTK_ADJUSTMENT (master_cycles_adj), 1, 0);
  gtk_widget_set_hexpand(master_cycles, TRUE);
  gtk_widget_show (master_cycles);
  gtk_grid_attach (GTK_GRID (grid7), master_cycles, 1, 1, 1, 1);
  gtk_widget_set_tooltip_text(master_cycles, "Specify the number of loops for the master turntable.");

  label36 = gtk_label_new ("Loops of the master turntable:");
  gtk_widget_show (label36);
  gtk_grid_attach (GTK_GRID (grid7), label36, 0, 1, 1, 1);

  label35 = gtk_label_new ("Loops of this turntable turntable:");
  gtk_widget_show (label35);
  gtk_grid_attach (GTK_GRID (grid7), label35, 0, 0, 1, 1);

  cycles_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 0);
  cycles = gtk_spin_button_new (GTK_ADJUSTMENT (cycles_adj), 1, 0);
  gtk_widget_set_hexpand(cycles, TRUE);
  gtk_widget_show (cycles);
  gtk_grid_attach (GTK_GRID (grid7), cycles, 1, 0, 1, 1);
  gtk_widget_set_tooltip_text(cycles, "Specify the number of loops of _this_ turntable.");

  create_event = gtk_check_button_new_with_mnemonic ("Record a sequencer event");
  gtk_widget_show (create_event);
  gtk_box_pack_start (GTK_BOX (vbox1), create_event, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (create_event), TRUE);


  cancel = gtk_button_new_with_mnemonic("_Cancel");
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_adjust), cancel, GTK_RESPONSE_CANCEL);
  gtk_widget_set_can_default(cancel, TRUE);

  ok = gtk_button_new_with_mnemonic("_OK");
  gtk_widget_show (ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_adjust), ok, GTK_RESPONSE_OK);
  gtk_widget_set_can_default(ok, TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_adjust, tx_adjust, "tx_adjust");
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_adjust, dialog_vbox2, "dialog_vbox2");
  TX_UI_HOOKUP_OBJECT (tx_adjust, vbox1, "vbox1");
  TX_UI_HOOKUP_OBJECT (tx_adjust, label34, "label34");
  TX_UI_HOOKUP_OBJECT (tx_adjust, grid7, "grid7");
  TX_UI_HOOKUP_OBJECT (tx_adjust, master_cycles, "master_cycles");
  TX_UI_HOOKUP_OBJECT (tx_adjust, label36, "label36");
  TX_UI_HOOKUP_OBJECT (tx_adjust, label35, "label35");
  TX_UI_HOOKUP_OBJECT (tx_adjust, cycles, "cycles");
  TX_UI_HOOKUP_OBJECT (tx_adjust, create_event, "create_event");
  TX_UI_HOOKUP_OBJECT (tx_adjust, cancel, "cancel");
  TX_UI_HOOKUP_OBJECT (tx_adjust, ok, "ok");

  return tx_adjust;
}

GtkWidget*
create_tx_options (GtkWindow* parent)
{
  GtkWidget *tx_options;
  GtkWidget *dialog_vbox3;
  GtkWidget *notebook1;
  GtkWidget *grid4;
  GtkWidget *label18;
  GtkWidget *hbox2;
  GtkWidget *oss_driver;
  GSList *oss_driver_group = NULL;
  GtkWidget *alsa_driver;
  GtkWidget *jack_driver;
  GtkWidget *pulse_driver;
  GtkWidget *use_realtime_label;
  GtkWidget *use_realtime;
  GtkWidget *label1;
  GtkWidget *grid5;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *oss_audio_device;
  GtkAdjustment *oss_buffers_adj;
  GtkWidget *oss_buffers;
  GtkWidget *oss_buffersize;
  GtkWidget *oss_samplerate;
  GtkWidget *label15;
  GtkWidget *grid6;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *alsa_audio_device;
  GtkWidget *alsa_samplerate;
  GtkWidget *alsa_period_time;
  GtkWidget *label32;
  GtkWidget *alsa_buffer_time;
  GtkWidget *label39;
  GtkWidget *alsa_free_hwstats;
  GtkWidget *label16;
  GtkWidget *grid1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *mouse_speed;
  GtkWidget *stop_sense_cycles;
  GtkWidget *label37;
  GtkWidget *vtt_inertia;
  GtkWidget *label4;
  GtkWidget *grid2;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *mainwin_tooltips;
  GtkWidget *update_idle;
  GtkWidget *update_delay;
  GtkWidget *vumeter_decay;

  GtkWidget *label_override;
  GtkWidget *label_knob_size;
  GtkWidget *knob_size;
  GtkWidget *override_knob_size;

  GtkWidget *label14;
  GtkWidget *startup_nagbox;
  GtkWidget *label12;
  GtkWidget *hbox1;
  GtkWidget *buttons_text_and_icon;
  GSList *buttons_text_and_icon_group = NULL;
  GtkWidget *buttons_icon_only;
  GtkWidget *buttons_text_only;
  GtkWidget *label38;
  GtkAdjustment *filename_length_adj;
  GtkWidget *filename_length;
  GtkWidget *label2;
  GtkWidget *grid8;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *wav_display_bg_focus;
  GtkWidget *wav_display_bg_no_focus;
  GtkWidget *wav_display_fg_focus;
  GtkWidget *wav_display_fg_no_focus;
  GtkWidget *wav_display_cursor;
  GtkWidget *wav_display_cursor_mute;
  GtkWidget *label41;
  GtkWidget *grid9;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *vu_meter_border_intensity;
  GtkWidget *vu_meter_bg;
  GtkWidget *vu_meter_normal;
  GtkWidget *vu_meter_loud;
  GtkWidget *label52;
  GtkWidget *grid3;
  GtkWidget *label13;
  GtkWidget *soundfile_editor;
  GtkWidget *label26;
  GtkWidget *prelisten_enabled;
  GtkWidget *label31;
  GtkWidget *ladspa_rdf_path;
  GtkWidget *label33;
  GtkWidget *compress_set_files;
  GtkWidget *label40;
  GtkWidget *reconnect_enabled;
  GtkWidget *label57;
  GtkWidget *quit_confirm;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *verbose_plugin_loading;
  GtkWidget *force_nonrt_plugins;
  GtkWidget *label3;
  GtkWidget *pref_reset;
  GtkWidget *pref_cancel;
  GtkWidget *pref_apply;
  GtkWidget *pref_ok;
  
  tx_options = gtk_dialog_new ();
  gtk_window_set_transient_for (GTK_WINDOW (tx_options), parent);
  gtk_window_set_title (GTK_WINDOW (tx_options), "terminatorX Preferences");

  dialog_vbox3 = gtk_dialog_get_content_area(GTK_DIALOG(tx_options));
  gtk_widget_show (dialog_vbox3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), notebook1, TRUE, TRUE, 0);

  grid4 = gtk_grid_new ();
  gtk_widget_show (grid4);
  gtk_container_add (GTK_CONTAINER (notebook1), grid4);
  gtk_container_set_border_width (GTK_CONTAINER (grid4), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid4), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid4), 2);

  label18 = gtk_label_new ("Driver:");
  gtk_widget_show (label18);
  gtk_grid_attach (GTK_GRID (grid4), label18, 0, 0, 1, 1);
  gtk_widget_set_halign(label18, GTK_ALIGN_START);

  hbox2 = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 5);
  gtk_widget_show (hbox2);
  gtk_grid_attach (GTK_GRID (grid4), hbox2, 1, 0, 1, 1);
  gtk_widget_set_hexpand(hbox2, TRUE);
  
  oss_driver = gtk_radio_button_new_with_mnemonic (NULL, "OSS");
  gtk_widget_show (oss_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), oss_driver, FALSE, FALSE, 0);
  gtk_widget_set_tooltip_text(oss_driver, "Use the OSS (Open Sound System) driver for audio output.");
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (oss_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (oss_driver));

  alsa_driver = gtk_radio_button_new_with_mnemonic (NULL, "ALSA");
  gtk_widget_show (alsa_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), alsa_driver, FALSE, FALSE, 0);
  gtk_widget_set_tooltip_text(alsa_driver, "Use the ALSA (Advanced Linux Sound System) driver for audio output.");
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (alsa_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (alsa_driver));

  jack_driver = gtk_radio_button_new_with_mnemonic (NULL, "JACK");
  gtk_widget_show (jack_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), jack_driver, FALSE, FALSE, 0);
  gtk_widget_set_tooltip_text(jack_driver, "Use the JACK (JACK Audio Connection Kit) driver for audio output.");
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (jack_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (jack_driver));
 
  pulse_driver = gtk_radio_button_new_with_mnemonic (NULL, "PULSE");
  gtk_widget_show (pulse_driver);
  gtk_box_pack_start (GTK_BOX (hbox2), pulse_driver, FALSE, FALSE, 0);
  gtk_widget_set_tooltip_text(pulse_driver, "Use the PULSE (PulseAudio) driver for audio output.");
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (pulse_driver), oss_driver_group);
  oss_driver_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (pulse_driver));

  use_realtime_label = gtk_label_new ("Scheduling:");
  gtk_widget_show (use_realtime_label);
  gtk_grid_attach (GTK_GRID (grid4), use_realtime_label, 0, 1, 1, 1);
  gtk_widget_set_halign(use_realtime_label, GTK_ALIGN_START);

  use_realtime = gtk_check_button_new_with_mnemonic ("Use realtime scheduling where available");
  gtk_widget_show (use_realtime);
  gtk_grid_attach (GTK_GRID (grid4), use_realtime, 1, 1, 1, 1);
  
  label1 = gtk_label_new ("Audio");
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  grid5 = gtk_grid_new ();
  gtk_widget_show (grid5);
  gtk_container_add (GTK_CONTAINER (notebook1), grid5);
  gtk_container_set_border_width (GTK_CONTAINER (grid5), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid5), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid5), 2);

  label21 = gtk_label_new ("Audio device:");
  gtk_widget_show (label21);
  gtk_grid_attach (GTK_GRID (grid5), label21, 0, 0, 1, 1);
  gtk_widget_set_halign(label21, GTK_ALIGN_START);

  label22 = gtk_label_new ("No. of buffers:");
  gtk_widget_show (label22);
  gtk_grid_attach (GTK_GRID (grid5), label22, 0, 1, 1, 1);
  gtk_widget_set_halign(label22, GTK_ALIGN_START);

  label23 = gtk_label_new ("Buffersize (2^x):");
  gtk_widget_show (label23);
  gtk_grid_attach (GTK_GRID (grid5), label23, 0, 2, 1, 1);
  gtk_widget_set_halign(label23, GTK_ALIGN_START);

  label24 = gtk_label_new ("Samplerate (Hz):");
  gtk_widget_show (label24);
  gtk_grid_attach (GTK_GRID (grid5), label24, 0, 3, 1, 1);
  gtk_widget_set_halign(label24, GTK_ALIGN_START);

  oss_audio_device = gtk_combo_box_text_new ();
//  g_object_set_data (G_OBJECT (GTK_COMBO_BOX (oss_audio_device)->popwin),
//                     "tXUiParentKey", oss_audio_device);
  gtk_widget_show (oss_audio_device);
  gtk_grid_attach (GTK_GRID (grid5), oss_audio_device, 1, 0, 1, 1);

  //combo_entry2 = GTK_COMBO (oss_audio_device)->entry;
  //gtk_widget_show (combo_entry2);
  gtk_widget_set_tooltip_text(oss_audio_device, "Select the audiodevice you want terminatorX to send its output to.");

  oss_buffers_adj = gtk_adjustment_new (2, 2, 5, 1, 10, 0);
  oss_buffers = gtk_spin_button_new (GTK_ADJUSTMENT (oss_buffers_adj), 1, 0);
  gtk_widget_set_hexpand(oss_buffers, TRUE);
  gtk_widget_show (oss_buffers);
  gtk_grid_attach (GTK_GRID (grid5), oss_buffers, 1, 1, 1, 1);
  gtk_widget_set_tooltip_text(oss_buffers, "Sets the number of kernel level audio buffers. Actually most systems should run just fine with two.");

  oss_buffersize = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (9, 8, 16, 1, 1, 1)));
  gtk_widget_show (oss_buffersize);
  gtk_grid_attach (GTK_GRID (grid5), oss_buffersize, 1, 2, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (oss_buffersize), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (oss_buffersize), 0);

  oss_samplerate = gtk_combo_box_text_new ();
  //g_object_set_data (G_OBJECT (GTK_COMBO (oss_samplerate)->popwin),
                     //"tXUiParentKey", oss_samplerate);
  gtk_widget_set_hexpand(oss_samplerate, TRUE);
  gtk_widget_show (oss_samplerate);
  gtk_grid_attach (GTK_GRID (grid5), oss_samplerate, 1, 3, 1, 1);

//  combo_entry3 = GTK_COMBO (oss_samplerate)->entry;
//  gtk_widget_show (combo_entry3);
  gtk_widget_set_tooltip_text(oss_samplerate, "Select the sampling to use for this audio device - the higher the better quality. Note that not all sampling rates are supported by all audio devices.");

  label15 = gtk_label_new ("Audio: OSS");
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label15);

  grid6 = gtk_grid_new ();
  gtk_widget_show (grid6);
  gtk_container_add (GTK_CONTAINER (notebook1), grid6);
  gtk_container_set_border_width (GTK_CONTAINER (grid6), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid6), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid6), 2);

  label27 = gtk_label_new ("Audio Device:");
  gtk_widget_show (label27);
  gtk_grid_attach (GTK_GRID (grid6), label27, 0, 0, 1, 1);
  gtk_widget_set_halign(label27, GTK_ALIGN_START);

  label29 = gtk_label_new ("Period Time (ms):");
  gtk_widget_show (label29);
  gtk_grid_attach (GTK_GRID (grid6), label29, 0, 2, 1, 1);
  gtk_widget_set_halign(label29, GTK_ALIGN_START);

  label30 = gtk_label_new ("Samplerate (Hz):");
  gtk_widget_show (label30);
  gtk_grid_attach (GTK_GRID (grid6), label30, 0, 3, 1, 1);
  gtk_widget_set_halign(label30, GTK_ALIGN_START);

  alsa_audio_device = gtk_combo_box_text_new ();
//  g_object_set_data (G_OBJECT (GTK_COMBO (alsa_audio_device)->popwin),
//                     "tXUiParentKey", alsa_audio_device);
  gtk_widget_set_hexpand(alsa_audio_device, TRUE);
  gtk_widget_show (alsa_audio_device);
  gtk_grid_attach (GTK_GRID (grid6), alsa_audio_device, 1, 0, 1, 1);

//  combo_entry4 = GTK_COMBO (alsa_audio_device)->entry;
//  gtk_widget_show (combo_entry4);

  alsa_samplerate = gtk_combo_box_text_new ();
//  g_object_set_data (G_OBJECT (GTK_COMBO (alsa_samplerate)->popwin),
//                     "tXUiParentKey", alsa_samplerate);
  gtk_widget_set_hexpand(alsa_samplerate, TRUE);
  gtk_widget_show (alsa_samplerate);
  gtk_grid_attach (GTK_GRID (grid6), alsa_samplerate, 1, 3, 1, 1);

//  combo_entry5 = GTK_COMBO (alsa_samplerate)->entry;
//  gtk_widget_show (combo_entry5);

  alsa_period_time = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (29, 10, 500, 1, 10, 10)));
  gtk_widget_show (alsa_period_time);
  gtk_grid_attach (GTK_GRID (grid6), alsa_period_time, 1, 2, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (alsa_period_time), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (alsa_period_time), 0);

  label32 = gtk_label_new ("Buffer Time (ms):");
  gtk_widget_show (label32);
  gtk_grid_attach (GTK_GRID (grid6), label32, 0, 1, 1, 1);
  gtk_widget_set_halign(label32, GTK_ALIGN_START);

  alsa_buffer_time = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (69, 10, 500, 1, 10, 10)));
  gtk_widget_show (alsa_buffer_time);
  gtk_grid_attach (GTK_GRID (grid6), alsa_buffer_time, 1, 1, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (alsa_buffer_time), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (alsa_buffer_time), 0);

  label39 = gtk_label_new ("Free HWstats:");
  gtk_widget_show (label39);
  gtk_grid_attach (GTK_GRID (grid6), label39, 0, 4, 1, 1);
  gtk_widget_set_halign(label39, GTK_ALIGN_START);

  alsa_free_hwstats = gtk_check_button_new_with_mnemonic ("Enabled");
  gtk_widget_show (alsa_free_hwstats);
  gtk_grid_attach (GTK_GRID (grid6), alsa_free_hwstats, 1, 4, 1, 1);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (alsa_free_hwstats), TRUE);

  label16 = gtk_label_new ("Audio: ALSA");
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label16);

  grid1 = gtk_grid_new ();
  gtk_widget_show (grid1);
  gtk_container_add (GTK_CONTAINER (notebook1), grid1);
  gtk_container_set_border_width (GTK_CONTAINER (grid1), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid1), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid1), 2);

  label6 = gtk_label_new ("Mouse speed:");
  gtk_widget_show (label6);
  gtk_grid_attach (GTK_GRID (grid1), label6, 0, 1, 1, 1);
  gtk_widget_set_halign(label6, GTK_ALIGN_START);

  label7 = gtk_label_new ("Stop-sense-cycles:");
  gtk_widget_show (label7);
  gtk_grid_attach (GTK_GRID (grid1), label7, 0, 2, 1, 1);
  gtk_widget_set_halign(label7, GTK_ALIGN_START);

  mouse_speed = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (0, -10, 10, 0.5, 0.1, 0.1)));
  gtk_widget_show (mouse_speed);
  gtk_widget_set_hexpand(mouse_speed, TRUE);
  gtk_grid_attach (GTK_GRID (grid1), mouse_speed, 1, 1, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (mouse_speed), GTK_POS_LEFT);

  stop_sense_cycles = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (80, 30, 250, 5, 1, 1)));
  gtk_widget_show (stop_sense_cycles);
  gtk_widget_set_hexpand(stop_sense_cycles, TRUE);
  gtk_grid_attach (GTK_GRID (grid1), stop_sense_cycles, 1, 2, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (stop_sense_cycles), GTK_POS_LEFT);

  label37 = gtk_label_new ("Turntable inertia:");
  gtk_widget_show (label37);
  gtk_grid_attach (GTK_GRID (grid1), label37, 0, 3, 1, 1);
  gtk_widget_set_halign(label37, GTK_ALIGN_START);

  vtt_inertia = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (11, 1, 310, 0.01, 1, 10)));
  gtk_widget_show (vtt_inertia);
  gtk_widget_set_hexpand(vtt_inertia, TRUE);
  gtk_grid_attach (GTK_GRID (grid1), vtt_inertia, 1, 3, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (vtt_inertia), GTK_POS_LEFT);

  label4 = gtk_label_new ("Input");
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);

  grid2 = gtk_grid_new ();
  gtk_widget_show (grid2);
  gtk_container_add (GTK_CONTAINER (notebook1), grid2);
  gtk_container_set_border_width (GTK_CONTAINER (grid2), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid2), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid2), 2);

  label8 = gtk_label_new ("Tooltips:");
  gtk_widget_show (label8);
  gtk_grid_attach (GTK_GRID (grid2), label8, 0, 1, 1, 1);
  gtk_widget_set_halign(label8, GTK_ALIGN_START);

  label9 = gtk_label_new ("Update idle (ms):");
  gtk_widget_show (label9);
  gtk_grid_attach (GTK_GRID (grid2), label9, 0, 3, 1, 1);
  gtk_widget_set_halign(label9, GTK_ALIGN_START);

  label10 = gtk_label_new ("Update delay (cycles):");
  gtk_widget_show (label10);
  gtk_grid_attach (GTK_GRID (grid2), label10, 0, 4, 1, 1);
  gtk_widget_set_halign(label10, GTK_ALIGN_START);

  label11 = gtk_label_new ("VU meter decay:");
  gtk_widget_show (label11);
  gtk_grid_attach (GTK_GRID (grid2), label11, 0, 5, 1, 1);
  gtk_widget_set_halign(label11, GTK_ALIGN_START);

  mainwin_tooltips = gtk_check_button_new_with_mnemonic ("Activate tooltips for the main wnidow");
  gtk_widget_show (mainwin_tooltips);
  gtk_grid_attach (GTK_GRID (grid2), mainwin_tooltips, 1, 1, 1, 1);
  gtk_widget_set_tooltip_text(mainwin_tooltips, "Enable tooltips for the terminatorX main window.");

  update_idle = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (11, 6, 100, 1, 10, 10)));
  gtk_widget_show (update_idle);
  gtk_grid_attach (GTK_GRID (grid2), update_idle, 1, 3, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (update_idle), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (update_idle), 0);

  update_delay = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 15, 1, 10, 10)));
  gtk_widget_show (update_delay);
  gtk_grid_attach (GTK_GRID (grid2), update_delay, 1, 4, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (update_delay), GTK_POS_LEFT);

  vumeter_decay = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (0.8, 0.8, 0.99, 0.01, 0.01, 0.001)));
  gtk_widget_show (vumeter_decay);
  gtk_grid_attach (GTK_GRID (grid2), vumeter_decay, 1, 5, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (vumeter_decay), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (vumeter_decay), 2);

  label14 = gtk_label_new ("Nagbox:");
  gtk_widget_show (label14);
  gtk_grid_attach (GTK_GRID (grid2), label14, 0, 0, 1, 1);
  gtk_widget_set_halign(label14, GTK_ALIGN_START);

  startup_nagbox = gtk_check_button_new_with_mnemonic ("Display nagbox on startup");
  gtk_widget_show (startup_nagbox);
  gtk_grid_attach (GTK_GRID (grid2), startup_nagbox, 1, 0, 1, 1);
  gtk_widget_set_tooltip_text(startup_nagbox, "Display nagbox on startup while loading data.");

  label12 = gtk_label_new ("Buttons:");
  gtk_widget_show (label12);
  gtk_grid_attach (GTK_GRID (grid2), label12, 0, 2, 1, 1);
  gtk_widget_set_halign(label12, GTK_ALIGN_START);

  hbox1 = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 5);
  gtk_widget_set_hexpand(hbox1, TRUE);
  gtk_widget_show (hbox1);
  gtk_grid_attach (GTK_GRID (grid2), hbox1, 1, 2, 1, 1);

  buttons_text_and_icon = gtk_radio_button_new_with_mnemonic (NULL, "Text + Icon");
  gtk_widget_show (buttons_text_and_icon);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_text_and_icon, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_text_and_icon), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_text_and_icon));

  buttons_icon_only = gtk_radio_button_new_with_mnemonic (NULL, "Icon Only");
  gtk_widget_show (buttons_icon_only);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_icon_only, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_icon_only), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_icon_only));

  buttons_text_only = gtk_radio_button_new_with_mnemonic (NULL, "Text Only");
  gtk_widget_show (buttons_text_only);
  gtk_box_pack_start (GTK_BOX (hbox1), buttons_text_only, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (buttons_text_only), buttons_text_and_icon_group);
  buttons_text_and_icon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (buttons_text_only));

  label38 = gtk_label_new ("Filename length:");
  gtk_widget_show (label38);
  gtk_grid_attach (GTK_GRID (grid2), label38, 0, 6, 1, 1);
  gtk_widget_set_halign(label38, GTK_ALIGN_START);

  filename_length_adj = gtk_adjustment_new (8, 3, 255, 1, 10, 0);
  filename_length = gtk_spin_button_new (GTK_ADJUSTMENT (filename_length_adj), 1, 0);
  gtk_widget_set_hexpand(filename_length, TRUE);
  gtk_widget_show (filename_length);
  gtk_grid_attach (GTK_GRID (grid2), filename_length, 1, 6, 1, 1);

	label_override = gtk_label_new ("Knob size:");
	gtk_widget_show(label_override);
	gtk_grid_attach(GTK_GRID(grid2), label_override, 0, 7, 1, 1);
	gtk_widget_set_halign(label_override, GTK_ALIGN_START);

  override_knob_size = gtk_check_button_new_with_mnemonic ("Override automatic adjustment");
  gtk_widget_show (override_knob_size);
  gtk_grid_attach (GTK_GRID (grid2), override_knob_size, 1, 7, 1, 1);
  gtk_widget_set_tooltip_text(override_knob_size, "Only when this option is activated the configured value for knob size will be used. Otherwise the size is adjusted automatically.");

	label_knob_size = gtk_label_new ("Size (override):");
  gtk_widget_show(label_knob_size);
  gtk_grid_attach(GTK_GRID(grid2), label_knob_size, 0, 8, 1, 1);
  gtk_widget_set_halign(label_knob_size, GTK_ALIGN_START);
  
  knob_size = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, GTK_ADJUSTMENT (gtk_adjustment_new (48, 16, 169, 1, 1, 1)));
  gtk_widget_show (knob_size);
  gtk_grid_attach (GTK_GRID (grid2), knob_size, 1, 8, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (knob_size), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (knob_size), 0);

  label2 = gtk_label_new ("User Interface");
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label2);

  grid8 = gtk_grid_new ();
  gtk_widget_show (grid8);
  gtk_container_add (GTK_CONTAINER (notebook1), grid8);
  gtk_grid_set_row_spacing (GTK_GRID (grid8), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid8), 2);

  label42 = gtk_label_new ("Background (focus):");
  gtk_widget_show (label42);
  gtk_grid_attach (GTK_GRID (grid8), label42, 0, 0, 1, 1);
  gtk_widget_set_halign(label42, GTK_ALIGN_START);

  label43 = gtk_label_new ("Background (no focus):");
  gtk_widget_show (label43);
  gtk_grid_attach (GTK_GRID (grid8), label43, 0, 1, 1, 1);
  gtk_widget_set_halign(label43, GTK_ALIGN_START);

  label44 = gtk_label_new ("Signal (focus):");
  gtk_widget_show (label44);
  gtk_grid_attach (GTK_GRID (grid8), label44, 0, 2, 1, 1);
  gtk_widget_set_halign(label44, GTK_ALIGN_START);

  label45 = gtk_label_new ("Signal (no focus):");
  gtk_widget_show (label45);
  gtk_grid_attach (GTK_GRID (grid8), label45, 0, 3, 1, 1);
  gtk_widget_set_halign(label45, GTK_ALIGN_START);

  label46 = gtk_label_new ("Cursor:");
  gtk_widget_show (label46);
  gtk_grid_attach (GTK_GRID (grid8), label46, 0, 4, 1, 1);
  gtk_widget_set_halign(label46, GTK_ALIGN_START);

  label47 = gtk_label_new ("Cursor (mute):");
  gtk_widget_show (label47);
  gtk_grid_attach (GTK_GRID (grid8), label47, 0, 5, 1, 1);
  gtk_widget_set_halign(label47, GTK_ALIGN_START);

  wav_display_bg_focus = gtk_button_new_with_mnemonic ("button1");
  gtk_widget_set_hexpand(wav_display_bg_focus , TRUE);
  gtk_widget_show (wav_display_bg_focus);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_bg_focus, 1, 0, 1, 1);

  wav_display_bg_no_focus = gtk_button_new_with_mnemonic ("button2");
  gtk_widget_set_hexpand(wav_display_bg_no_focus , TRUE);
  gtk_widget_show (wav_display_bg_no_focus);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_bg_no_focus, 1, 1, 1, 1);

  wav_display_fg_focus = gtk_button_new_with_mnemonic ("button3");
  gtk_widget_set_hexpand(wav_display_fg_focus , TRUE);
  gtk_widget_show (wav_display_fg_focus);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_fg_focus, 1, 2, 1, 1);

  wav_display_fg_no_focus = gtk_button_new_with_mnemonic ("button4");
  gtk_widget_set_hexpand(wav_display_fg_no_focus , TRUE);
  gtk_widget_show (wav_display_fg_no_focus);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_fg_no_focus, 1, 3, 1, 1);

  wav_display_cursor = gtk_button_new_with_mnemonic ("button5");
  gtk_widget_set_hexpand(wav_display_cursor , TRUE);
  gtk_widget_show (wav_display_cursor);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_cursor, 1, 4, 1, 1);

  wav_display_cursor_mute = gtk_button_new_with_mnemonic ("button6");
  gtk_widget_set_hexpand(wav_display_cursor_mute , TRUE);
  gtk_widget_show (wav_display_cursor_mute);
  gtk_grid_attach (GTK_GRID (grid8), wav_display_cursor_mute, 1, 5, 1, 1);

  label41 = gtk_label_new ("Audio Colors");
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label41);

  grid9 = gtk_grid_new ();
  gtk_widget_show (grid9);
  gtk_container_add (GTK_CONTAINER (notebook1), grid9);
  gtk_container_set_border_width (GTK_CONTAINER (grid9), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid9), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid9), 2);

  label53 = gtk_label_new ("Background:");
  gtk_widget_show (label53);
  gtk_grid_attach (GTK_GRID (grid9), label53, 0, 0, 1, 1);
  gtk_widget_set_halign(label53, GTK_ALIGN_START);

  label54 = gtk_label_new ("Regular Signal:");
  gtk_widget_show (label54);
  gtk_grid_attach (GTK_GRID (grid9), label54, 0, 1, 1, 1);
  gtk_widget_set_halign(label54, GTK_ALIGN_START);

  label55 = gtk_label_new ("Loud Signal:");
  gtk_widget_show (label55);
  gtk_grid_attach (GTK_GRID (grid9), label55, 0, 2, 1, 1);
  gtk_widget_set_halign(label55, GTK_ALIGN_START);

  label56 = gtk_label_new ("Scale Opacity:");
  gtk_widget_show (label56);
  gtk_grid_attach (GTK_GRID (grid9), label56, 0, 3, 1, 1);
  gtk_widget_set_halign(label56, GTK_ALIGN_START);

  vu_meter_border_intensity = gtk_scale_new (GTK_ORIENTATION_HORIZONTAL,  GTK_ADJUSTMENT (gtk_adjustment_new (0.07, 0, 1, 0.01, 0, 0)));
  gtk_widget_set_hexpand(vu_meter_border_intensity, TRUE);
  gtk_widget_show (vu_meter_border_intensity);
  gtk_grid_attach (GTK_GRID (grid9), vu_meter_border_intensity, 1, 3, 1, 1);
  gtk_scale_set_value_pos (GTK_SCALE (vu_meter_border_intensity), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (vu_meter_border_intensity), 2);

  vu_meter_bg = gtk_button_new_with_mnemonic ("button7");
  gtk_widget_show (vu_meter_bg);
  gtk_grid_attach (GTK_GRID (grid9), vu_meter_bg, 1, 0, 1, 1);

  vu_meter_normal = gtk_button_new_with_mnemonic ("button8");
  gtk_widget_show (vu_meter_normal);
  gtk_grid_attach (GTK_GRID (grid9), vu_meter_normal, 1, 1, 1, 1);

  vu_meter_loud = gtk_button_new_with_mnemonic ("button9");
  gtk_widget_show (vu_meter_loud);
  gtk_grid_attach (GTK_GRID (grid9), vu_meter_loud, 1, 2, 1, 1);

  label52 = gtk_label_new ("VU Colors");
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label52);

  grid3 = gtk_grid_new ();
  gtk_widget_show (grid3);
  gtk_container_add (GTK_CONTAINER (notebook1), grid3);
  gtk_container_set_border_width (GTK_CONTAINER (grid3), 4);
  gtk_grid_set_row_spacing (GTK_GRID (grid3), 2);
  gtk_grid_set_column_spacing (GTK_GRID (grid3), 2);

  label13 = gtk_label_new ("Soundfile editor:");
  gtk_widget_show (label13);
  gtk_grid_attach (GTK_GRID (grid3), label13, 0, 0, 1, 1);
  gtk_widget_set_halign(label13, GTK_ALIGN_START);

  soundfile_editor = gtk_entry_new ();
  gtk_widget_set_hexpand(soundfile_editor, TRUE);
  gtk_widget_show (soundfile_editor);
  gtk_grid_attach (GTK_GRID (grid3), soundfile_editor, 1, 0, 1, 1);
  gtk_widget_set_tooltip_text(soundfile_editor, "Enter the command to run your favourite soundfile editor. It will be started when you choose \"Edit File\" from the turntable's file menu.");

  label26 = gtk_label_new ("Pre-listen:");
  gtk_widget_show (label26);
  gtk_grid_attach (GTK_GRID (grid3), label26, 0, 3, 1, 1);
  gtk_widget_set_halign(label26, GTK_ALIGN_START);

  prelisten_enabled = gtk_check_button_new_with_mnemonic ("Play audiofiles in file dialogs");
  gtk_widget_show (prelisten_enabled);
  gtk_grid_attach (GTK_GRID (grid3), prelisten_enabled, 1, 3, 1, 1);
  gtk_widget_set_tooltip_text(prelisten_enabled, "When enabled soundfiles will be playedback when selected in a file dialog (before loading them).");

  label31 = gtk_label_new ("LADSPA RDF path:");
  gtk_widget_show (label31);
  gtk_grid_attach (GTK_GRID (grid3), label31, 0, 1, 1, 1);
  gtk_widget_set_halign(label31, GTK_ALIGN_START);

  ladspa_rdf_path = gtk_entry_new ();
  gtk_widget_show (ladspa_rdf_path);
  gtk_grid_attach (GTK_GRID (grid3), ladspa_rdf_path, 1, 1, 1, 1);

  label33 = gtk_label_new ("Compression:");
  gtk_widget_show (label33);
  gtk_grid_attach (GTK_GRID (grid3), label33, 0, 2, 1, 1);
  gtk_widget_set_halign(label33, GTK_ALIGN_START);

  compress_set_files = gtk_check_button_new_with_mnemonic ("Compress terminatorX set files");
  gtk_widget_show (compress_set_files);
  gtk_grid_attach (GTK_GRID (grid3), compress_set_files, 1, 2, 1, 1);

  label40 = gtk_label_new ("MIDI:");
  gtk_widget_show (label40);
  gtk_grid_attach (GTK_GRID (grid3), label40, 0, 4, 1, 1);
  gtk_widget_set_halign(label40, GTK_ALIGN_START);

  reconnect_enabled = gtk_check_button_new_with_mnemonic ("Restore MIDI connections on startup");
  gtk_widget_show (reconnect_enabled);
  gtk_grid_attach (GTK_GRID (grid3), reconnect_enabled, 1, 4, 1, 1);
  gtk_widget_set_tooltip_text(reconnect_enabled, "When enabled soundfiles will be playedback when selected in a file dialog (before loading them).");

  label57 = gtk_label_new ("Quit:");
  gtk_widget_show (label57);
  gtk_grid_attach (GTK_GRID (grid3), label57, 0, 5, 1, 1);
  gtk_widget_set_halign(label57, GTK_ALIGN_START);

  quit_confirm = gtk_check_button_new_with_mnemonic ("Ask for \"Quit\" confirmation");
  gtk_widget_show (quit_confirm);
  gtk_grid_attach (GTK_GRID (grid3), quit_confirm, 1, 5, 1, 1);

  label58 = gtk_label_new ("Plugins:");
  gtk_widget_show (label58);
  gtk_grid_attach (GTK_GRID (grid3), label58, 0, 6, 1, 1);
  gtk_widget_set_halign(label58, GTK_ALIGN_START);

  label59 = gtk_label_new ("");
  gtk_widget_show (label59);
  gtk_grid_attach (GTK_GRID (grid3), label59, 0, 7, 1, 1);
  gtk_widget_set_halign(label59, GTK_ALIGN_START);

  verbose_plugin_loading = gtk_check_button_new_with_mnemonic ("Verbose plugin loading");
  gtk_widget_show (verbose_plugin_loading);
  gtk_grid_attach (GTK_GRID (grid3), verbose_plugin_loading, 1, 6, 1, 1);

  force_nonrt_plugins = gtk_check_button_new_with_mnemonic ("Force loading of \"non-RT\" plugins ");
  gtk_widget_show (force_nonrt_plugins);
  gtk_grid_attach (GTK_GRID (grid3), force_nonrt_plugins, 1, 7, 1, 1);

  label3 = gtk_label_new ("Misc");
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 7), label3);


  pref_reset = gtk_button_new_with_mnemonic("_Revert");
  gtk_widget_show (pref_reset);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_reset, 0);
  gtk_widget_set_can_default(pref_reset, TRUE);
  
  pref_cancel = gtk_button_new_with_mnemonic("_Cancel");
  gtk_widget_show (pref_cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_cancel, GTK_RESPONSE_CANCEL);
  gtk_widget_set_can_default(pref_cancel, TRUE);
  
  pref_apply = gtk_button_new_with_mnemonic("_Apply");
  gtk_widget_show (pref_apply);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_apply, GTK_RESPONSE_APPLY);
  gtk_widget_set_can_default(pref_apply, TRUE);

  pref_ok = gtk_button_new_with_mnemonic("_OK");
  gtk_widget_show (pref_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_options), pref_ok, GTK_RESPONSE_OK);
  gtk_widget_set_can_default(pref_ok, TRUE);
  
  g_signal_connect ((gpointer) tx_options, "destroy",
                    G_CALLBACK (on_tx_options_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) alsa_buffer_time, "value_changed",
                            G_CALLBACK (on_alsa_buffer_time_value_changed),
                            G_OBJECT (alsa_period_time));
  g_signal_connect_swapped ((gpointer) wav_display_bg_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_bg_focus));
  g_signal_connect_swapped ((gpointer) wav_display_bg_no_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_bg_no_focus));
  g_signal_connect_swapped ((gpointer) wav_display_fg_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_fg_focus));
  g_signal_connect_swapped ((gpointer) wav_display_fg_no_focus, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_fg_no_focus));
  g_signal_connect_swapped ((gpointer) wav_display_cursor, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_cursor));
  g_signal_connect_swapped ((gpointer) wav_display_cursor_mute, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (wav_display_cursor_mute));
  g_signal_connect_swapped ((gpointer) vu_meter_bg, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (vu_meter_bg));
  g_signal_connect_swapped ((gpointer) vu_meter_normal, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (vu_meter_normal));
  g_signal_connect_swapped ((gpointer) vu_meter_loud, "clicked",
                            G_CALLBACK (color_clicked),
                            G_OBJECT (vu_meter_loud));
  g_signal_connect ((gpointer) pref_reset, "clicked",
                    G_CALLBACK (on_pref_reset_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_cancel, "clicked",
                    G_CALLBACK (on_pref_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_apply, "clicked",
                    G_CALLBACK (on_pref_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_ok, "clicked",
                    G_CALLBACK (on_pref_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_options, tx_options, "tx_options");
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_options, dialog_vbox3, "dialog_vbox3");
  TX_UI_HOOKUP_OBJECT (tx_options, notebook1, "notebook1");
  TX_UI_HOOKUP_OBJECT (tx_options, grid4, "grid4");
  TX_UI_HOOKUP_OBJECT (tx_options, label18, "label18");
  TX_UI_HOOKUP_OBJECT (tx_options, hbox2, "hbox2");
  TX_UI_HOOKUP_OBJECT (tx_options, oss_driver, "oss_driver");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_driver, "alsa_driver");
  TX_UI_HOOKUP_OBJECT (tx_options, jack_driver, "jack_driver");
  TX_UI_HOOKUP_OBJECT (tx_options, pulse_driver, "pulse_driver");
  TX_UI_HOOKUP_OBJECT (tx_options, use_realtime_label, "use_realtime_label");
  TX_UI_HOOKUP_OBJECT (tx_options, use_realtime, "use_realtime");
  TX_UI_HOOKUP_OBJECT (tx_options, label1, "label1");
  TX_UI_HOOKUP_OBJECT (tx_options, grid5, "grid5");
  TX_UI_HOOKUP_OBJECT (tx_options, label21, "label21");
  TX_UI_HOOKUP_OBJECT (tx_options, label22, "label22");
  TX_UI_HOOKUP_OBJECT (tx_options, label23, "label23");
  TX_UI_HOOKUP_OBJECT (tx_options, label24, "label24");
  TX_UI_HOOKUP_OBJECT (tx_options, oss_audio_device, "oss_audio_device");
  TX_UI_HOOKUP_OBJECT (tx_options, oss_buffers, "oss_buffers");
  TX_UI_HOOKUP_OBJECT (tx_options, oss_buffersize, "oss_buffersize");
  TX_UI_HOOKUP_OBJECT (tx_options, oss_samplerate, "oss_samplerate");
  TX_UI_HOOKUP_OBJECT (tx_options, label15, "label15");
  TX_UI_HOOKUP_OBJECT (tx_options, grid6, "grid6");
  TX_UI_HOOKUP_OBJECT (tx_options, label27, "label27");
  TX_UI_HOOKUP_OBJECT (tx_options, label29, "label29");
  TX_UI_HOOKUP_OBJECT (tx_options, label30, "label30");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_audio_device, "alsa_audio_device");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_samplerate, "alsa_samplerate");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_period_time, "alsa_period_time");
  TX_UI_HOOKUP_OBJECT (tx_options, label32, "label32");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_buffer_time, "alsa_buffer_time");
  TX_UI_HOOKUP_OBJECT (tx_options, label39, "label39");
  TX_UI_HOOKUP_OBJECT (tx_options, alsa_free_hwstats, "alsa_free_hwstats");
  TX_UI_HOOKUP_OBJECT (tx_options, label16, "label16");
  TX_UI_HOOKUP_OBJECT (tx_options, grid1, "grid1");
  TX_UI_HOOKUP_OBJECT (tx_options, label6, "label6");
  TX_UI_HOOKUP_OBJECT (tx_options, label7, "label7");
  TX_UI_HOOKUP_OBJECT (tx_options, mouse_speed, "mouse_speed");
  TX_UI_HOOKUP_OBJECT (tx_options, stop_sense_cycles, "stop_sense_cycles");
  TX_UI_HOOKUP_OBJECT (tx_options, label37, "label37");
  TX_UI_HOOKUP_OBJECT (tx_options, vtt_inertia, "vtt_inertia");
  TX_UI_HOOKUP_OBJECT (tx_options, label4, "label4");
  TX_UI_HOOKUP_OBJECT (tx_options, grid2, "grid2");
  TX_UI_HOOKUP_OBJECT (tx_options, label8, "label8");
  TX_UI_HOOKUP_OBJECT (tx_options, label9, "label9");
  TX_UI_HOOKUP_OBJECT (tx_options, label10, "label10");
  TX_UI_HOOKUP_OBJECT (tx_options, label11, "label11");
  TX_UI_HOOKUP_OBJECT (tx_options, mainwin_tooltips, "mainwin_tooltips");
  TX_UI_HOOKUP_OBJECT (tx_options, update_idle, "update_idle");
  TX_UI_HOOKUP_OBJECT (tx_options, update_delay, "update_delay");
  TX_UI_HOOKUP_OBJECT (tx_options, vumeter_decay, "vumeter_decay");
  TX_UI_HOOKUP_OBJECT (tx_options, label14, "label14");
  TX_UI_HOOKUP_OBJECT (tx_options, startup_nagbox, "startup_nagbox");
  TX_UI_HOOKUP_OBJECT (tx_options, label12, "label12");
  TX_UI_HOOKUP_OBJECT (tx_options, hbox1, "hbox1");
  TX_UI_HOOKUP_OBJECT (tx_options, buttons_text_and_icon, "buttons_text_and_icon");
  TX_UI_HOOKUP_OBJECT (tx_options, buttons_icon_only, "buttons_icon_only");
  TX_UI_HOOKUP_OBJECT (tx_options, buttons_text_only, "buttons_text_only");
  TX_UI_HOOKUP_OBJECT (tx_options, label38, "label38");
  TX_UI_HOOKUP_OBJECT (tx_options, filename_length, "filename_length");
  TX_UI_HOOKUP_OBJECT (tx_options, label2, "label2");
  TX_UI_HOOKUP_OBJECT (tx_options, grid8, "grid8");
  TX_UI_HOOKUP_OBJECT (tx_options, label42, "label42");
  TX_UI_HOOKUP_OBJECT (tx_options, label43, "label43");
  TX_UI_HOOKUP_OBJECT (tx_options, label44, "label44");
  TX_UI_HOOKUP_OBJECT (tx_options, label45, "label45");
  TX_UI_HOOKUP_OBJECT (tx_options, label46, "label46");
  TX_UI_HOOKUP_OBJECT (tx_options, label47, "label47");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_bg_focus, "wav_display_bg_focus");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_bg_no_focus, "wav_display_bg_no_focus");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_fg_focus, "wav_display_fg_focus");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_fg_no_focus, "wav_display_fg_no_focus");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_cursor, "wav_display_cursor");
  TX_UI_HOOKUP_OBJECT (tx_options, wav_display_cursor_mute, "wav_display_cursor_mute");
  TX_UI_HOOKUP_OBJECT (tx_options, label41, "label41");
  TX_UI_HOOKUP_OBJECT (tx_options, grid9, "grid9");
  TX_UI_HOOKUP_OBJECT (tx_options, label53, "label53");
  TX_UI_HOOKUP_OBJECT (tx_options, label54, "label54");
  TX_UI_HOOKUP_OBJECT (tx_options, label55, "label55");
  TX_UI_HOOKUP_OBJECT (tx_options, label56, "label56");
  TX_UI_HOOKUP_OBJECT (tx_options, vu_meter_border_intensity, "vu_meter_border_intensity");
  TX_UI_HOOKUP_OBJECT (tx_options, vu_meter_bg, "vu_meter_bg");
  TX_UI_HOOKUP_OBJECT (tx_options, vu_meter_normal, "vu_meter_normal");
  TX_UI_HOOKUP_OBJECT (tx_options, vu_meter_loud, "vu_meter_loud");
  TX_UI_HOOKUP_OBJECT (tx_options, label52, "label52");
  TX_UI_HOOKUP_OBJECT (tx_options, grid3, "grid3");
  TX_UI_HOOKUP_OBJECT (tx_options, label13, "label13");
  TX_UI_HOOKUP_OBJECT (tx_options, soundfile_editor, "soundfile_editor");
  TX_UI_HOOKUP_OBJECT (tx_options, label26, "label26");
  TX_UI_HOOKUP_OBJECT (tx_options, prelisten_enabled, "prelisten_enabled");
  TX_UI_HOOKUP_OBJECT (tx_options, label31, "label31");
  TX_UI_HOOKUP_OBJECT (tx_options, ladspa_rdf_path, "ladspa_rdf_path");
  TX_UI_HOOKUP_OBJECT (tx_options, label33, "label33");
  TX_UI_HOOKUP_OBJECT (tx_options, compress_set_files, "compress_set_files");
  TX_UI_HOOKUP_OBJECT (tx_options, label40, "label40");
  TX_UI_HOOKUP_OBJECT (tx_options, reconnect_enabled, "reconnect_enabled");
  TX_UI_HOOKUP_OBJECT (tx_options, label57, "label57");
  TX_UI_HOOKUP_OBJECT (tx_options, quit_confirm, "quit_confirm");
  TX_UI_HOOKUP_OBJECT (tx_options, label58, "label58");
  TX_UI_HOOKUP_OBJECT (tx_options, label59, "label59");
  TX_UI_HOOKUP_OBJECT (tx_options, verbose_plugin_loading, "verbose_plugin_loading");
  TX_UI_HOOKUP_OBJECT (tx_options, force_nonrt_plugins, "force_nonrt_plugins");
  TX_UI_HOOKUP_OBJECT (tx_options, label3, "label3");
  TX_UI_HOOKUP_OBJECT (tx_options, pref_reset, "pref_reset");
  TX_UI_HOOKUP_OBJECT (tx_options, pref_cancel, "pref_cancel");
  TX_UI_HOOKUP_OBJECT (tx_options, pref_apply, "pref_apply");
  TX_UI_HOOKUP_OBJECT (tx_options, pref_ok, "pref_ok");
  TX_UI_HOOKUP_OBJECT (tx_options, label_override, "label_override");
  TX_UI_HOOKUP_OBJECT (tx_options, label_knob_size, "label_knob_size");
  TX_UI_HOOKUP_OBJECT (tx_options, knob_size, "knob_size");
  TX_UI_HOOKUP_OBJECT (tx_options, override_knob_size, "override_knob_size");

  return tx_options;
}

GtkWidget*
create_tx_del_mode (void)
{
  GtkWidget *tx_del_mode;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox2;
  GtkWidget *delmode_label;
  GtkWidget *hbox3;
  GtkWidget *vbox3;
  GtkWidget *all_events;
  GSList *all_events_group = NULL;
  GtkWidget *upto_current;
  GtkWidget *from_current;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  tx_del_mode = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tx_del_mode), "Choose Events to Delete");

  dialog_vbox4 = gtk_dialog_get_content_area(GTK_DIALOG (tx_del_mode));
  gtk_widget_show (dialog_vbox4);

  vbox2 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 2);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 4);

  delmode_label = gtk_label_new ("Select which events to delete.");
  gtk_widget_show (delmode_label);
  gtk_box_pack_start (GTK_BOX (vbox2), delmode_label, TRUE, FALSE, 0);

  hbox3 = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, TRUE, FALSE, 0);

  vbox3 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox3, TRUE, FALSE, 0);

  all_events = gtk_radio_button_new_with_mnemonic (NULL, "Complete song");
  gtk_widget_show (all_events);
  gtk_box_pack_start (GTK_BOX (vbox3), all_events, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (all_events), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (all_events));

  upto_current = gtk_radio_button_new_with_mnemonic (NULL, "Upto the current song position");
  gtk_widget_show (upto_current);
  gtk_box_pack_start (GTK_BOX (vbox3), upto_current, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (upto_current), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (upto_current));

  from_current = gtk_radio_button_new_with_mnemonic (NULL, "From the current song position");
  gtk_widget_show (from_current);
  gtk_box_pack_start (GTK_BOX (vbox3), from_current, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (from_current), all_events_group);
  all_events_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (from_current));


  cancelbutton1 = gtk_button_new_with_mnemonic("_Cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_del_mode), cancelbutton1, GTK_RESPONSE_CANCEL);
  gtk_widget_set_can_default(cancelbutton1, TRUE);

  okbutton1 = gtk_button_new_with_mnemonic("_OK");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (tx_del_mode), okbutton1, GTK_RESPONSE_OK);
  gtk_widget_set_can_default(okbutton1, TRUE);

  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_del_mode_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_del_mode_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_del_mode, tx_del_mode, "tx_del_mode");
  TX_UI_HOOKUP_OBJECT_NO_REF (tx_del_mode, dialog_vbox4, "dialog_vbox4");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, vbox2, "vbox2");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, delmode_label, "delmode_label");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, hbox3, "hbox3");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, vbox3, "vbox3");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, all_events, "all_events");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, upto_current, "upto_current");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, from_current, "from_current");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, cancelbutton1, "cancelbutton1");
  TX_UI_HOOKUP_OBJECT (tx_del_mode, okbutton1, "okbutton1");

  return tx_del_mode;
}

GtkWidget*
create_tX_midilearn (void)
{
  GtkWidget *tX_midilearn;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox4;
  GtkWidget *midilabel;
  GtkWidget *cancel;

  tX_midilearn = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (tX_midilearn), "MIDI Learn");

  dialog_vbox5 = gtk_dialog_get_content_area(GTK_DIALOG (tX_midilearn));
  gtk_widget_show (dialog_vbox5);

  vbox4 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 4);

  midilabel = gtk_label_new ("Waiting for MIDI event....");
  gtk_widget_show (midilabel);
  gtk_box_pack_start (GTK_BOX (vbox4), midilabel, TRUE, TRUE, 0);


  cancel = gtk_button_new_with_mnemonic("_Cancel");
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (tX_midilearn), cancel, GTK_RESPONSE_CANCEL);
  gtk_widget_set_can_default(cancel, TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  TX_UI_HOOKUP_OBJECT_NO_REF (tX_midilearn, tX_midilearn, "tX_midilearn");
  TX_UI_HOOKUP_OBJECT_NO_REF (tX_midilearn, dialog_vbox5, "dialog_vbox5");
  TX_UI_HOOKUP_OBJECT (tX_midilearn, vbox4, "vbox4");
  TX_UI_HOOKUP_OBJECT (tX_midilearn, midilabel, "midilabel");
  TX_UI_HOOKUP_OBJECT (tX_midilearn, cancel, "cancel");

  return tX_midilearn;
}

GtkWidget*
create_tX_color_chooser (GtkWidget *parent)
{
  GtkWidget *tX_color_chooser;
  GValue value = { 0, };
  g_value_init(&value, GTK_TYPE_WIDGET);

  tX_color_chooser = gtk_color_chooser_dialog_new ("Select Color", GTK_WINDOW(parent));
  gtk_window_set_resizable (GTK_WINDOW (tX_color_chooser), FALSE);
  
  gtk_color_chooser_set_use_alpha(GTK_COLOR_CHOOSER(tX_color_chooser), FALSE);   

  g_signal_connect(tX_color_chooser, "response", G_CALLBACK(color_response), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  TX_UI_HOOKUP_OBJECT_NO_REF (tX_color_chooser, tX_color_chooser, "tX_color_chooser");
  
  return tX_color_chooser;
}

