/*
 * This file is no longer being generated by Glade and contains hand
 * crafted code.
 */

#pragma once

GtkWidget* create_tx_adjust(void);
GtkWidget* create_tx_options(GtkWindow* parent);
GtkWidget* create_tx_del_mode(void);
GtkWidget* create_tX_midilearn(void);
GtkWidget* create_tX_color_chooser(GtkWidget* parentS);
