name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: ["CC=clang CXX=clang++", "CC=gcc CXX=g++"]

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install ladspa-sdk libasound2-dev libatk1.0-dev libaudiofile-dev \
                            libcap2-dev libglib2.0-dev libgtk-3-dev libice-dev \
                            libjack-dev liblrdf0-dev libmad0-dev libpango1.0-dev \
                            libpulse-dev libsm-dev libvorbis-dev libx11-dev libxext-dev \
                            libxi-dev libxml2-dev mpg321 sox vorbis-tools yelp-tools zlib1g-dev
    - name: Run Compile Test using ${{ matrix.target }}
      run: |
        ./autogen.sh
        ./configure ${{ matrix.target }}
        make -j $(nproc)
